import OddZeta.Family.CertDef
import OddZeta.Family.Regions
import OddZeta.Family.SmallSound
import OddZeta.Family.SmallChk1
import OddZeta.Family.SmallChk2
import OddZeta.Family.SmallChk3
import OddZeta.Family.SmallChk4
import OddZeta.Family.SmallChk5
import OddZeta.Family.SmallChk6
import OddZeta.Family.SmallChk7
import OddZeta.Family.SmallChk8
import OddZeta.Family.SmallChk9
import OddZeta.Family.SmallChk10

/-!
# Certificates for the family: `3 ≤ r ≤ 299`, one kernel-checked certificate per `r`

For each odd `r ≤ 299`: the saddle point `u*` (contraction mapping around a rational `ũ`), the path
`-i∞ → P_R = 20 + i y_R → bot → σ → top → P_L → -2` (`y_R ≤ -1/4`, `P_L` near the midpoint of
`[top, -2]`); the ray is covered for all `r` by `regRay_bound`, the three segments by grid checks
(Lemma 4.8 of the note). The checker `Small.famCertOK` and its soundness `Small.famCert_of_ok` are
in `SmallMach.lean` / `SmallSound.lean`, the data and the kernel checks (generated by
`scripts/small_cert_gen.py`) in `SmallChk1.lean`, …, `SmallChk10.lean`.
-/

namespace OddZeta

namespace Small

/-- The certificate data for all odd `3 ≤ r ≤ 299`. -/
def allData : List (ℕ × SmData) :=
  chunk1 ++ chunk2 ++ chunk3 ++ chunk4 ++ chunk5 ++ chunk6 ++ chunk7 ++ chunk8 ++ chunk9 ++ chunk10

theorem allData_cover :
    ∀ r < 300, r % 2 = 1 → 3 ≤ r → (allData.any fun p => p.1 == r) = true := by
  decide +kernel

end Small

/-- Each certificate is taken from its own chunk (`chunkK_ok`), so that no checker has to evaluate
all the chunks at once. -/
theorem famCert_small (r : ℕ) (hr : Odd r) (h3 : 3 ≤ r) (h299 : r ≤ 299) : FamCert r := by
  obtain ⟨p, hp, hpr⟩ :=
    List.any_eq_true.1 (Small.allData_cover r (by omega) (Nat.odd_iff.1 hr) h3)
  rw [beq_iff_eq] at hpr
  rw [← hpr]
  simp only [Small.allData, List.mem_append] at hp
  rcases hp with (((((((((hp | hp) | hp) | hp) | hp) | hp) | hp) | hp) | hp) | hp)
  · exact Small.famCert_of_ok (Small.chunk1_ok p hp)
  · exact Small.famCert_of_ok (Small.chunk2_ok p hp)
  · exact Small.famCert_of_ok (Small.chunk3_ok p hp)
  · exact Small.famCert_of_ok (Small.chunk4_ok p hp)
  · exact Small.famCert_of_ok (Small.chunk5_ok p hp)
  · exact Small.famCert_of_ok (Small.chunk6_ok p hp)
  · exact Small.famCert_of_ok (Small.chunk7_ok p hp)
  · exact Small.famCert_of_ok (Small.chunk8_ok p hp)
  · exact Small.famCert_of_ok (Small.chunk9_ok p hp)
  · exact Small.famCert_of_ok (Small.chunk10_ok p hp)

end OddZeta
