import OddZeta.Family.Num

/-!
# Kernel-checked bounds for the regions of Lemma 8.7

Grids (generated by `scripts/regions_cert.py`) and `decide +kernel` checks for the suprema of
`Re g` and of `Re e + 2π Im u` on the rectangles `B_L`, `B_R`, on the segment `[P_L, -2]` and on
the lower ray `{20 - i y : y ≥ 1/4}` (`Num.lean`: `chkRect`, `chkSeg`), together with the
monotonicity of `Re g` and `Re e` on the ray (Lemma 8.6(ii) of the note).
-/

namespace OddZeta.FamNum

open Complex Set OddZeta.Cert OddZeta.Cert.QI

/-! ### The checks -/

theorem chk_BL_G : chkRect (fun x y => gPt x y 50) g2Box okBox (2092953 / 1000000)
    (2702953 / 1000000) (-523633 / 1000000) 0 (-2322435 / 10000) [] [] [] [] = true := by
  decide +kernel

theorem chk_BL_E : chkRect (fun x y => esPt x y 50) e2Box okBoxE (2092953 / 1000000)
    (2702953 / 1000000) (-523633 / 1000000) 0 (-93025 / 10000) [] [] [] [] = true := by
  decide +kernel

theorem chk_BR_G : chkRect (fun x y => gPt x y 50) g2Box okBox (5604839 / 1000000) 20
    (-827198 / 1000000) 0 (-2321627 / 10000) [mkRat 1 8, mkRat 5 8] [mkRat 1 8, mkRat 5 8] [] [] =
    true := by
  decide +kernel

theorem chk_BR_E : chkRect (fun x y => esPt x y 50) e2Box okBoxE (5604839 / 1000000) 20
    (-827198 / 1000000) 0 (-93914 / 10000) [] [] [] [] = true := by
  decide +kernel

/-- `[P_L, -2]` for `e`: `P_L = 2092953/10⁶ - i/4`, direction `-2 - P_L`. -/
theorem chk_PL_E : chkSeg (fun x y => esPt x y 50) e2Box okBoxE (2092953 / 1000000) (-1 / 4)
    (-4092953 / 1000000) (1 / 4) (-91937 / 10000) [] = true := by
  decide +kernel

/-- `[P_L, Q]` for `g`, `Q = P_L + (63/64)(-2 - P_L)`. -/
theorem chk_PL_G : chkSeg (fun x y => gPt x y 50) g2Box okBox (2092953 / 1000000) (-1 / 4)
    (-257856039 / 64000000) (63 / 256) (-2325535 / 10000)
    [mkRat 1 4, mkRat 7 16, mkRat 23 32] = true := by
  decide +kernel

/-- The last piece `[Q, -2)` of `[P_L, -2]` for `g` (one-sided, from `Q = qx + qy i`). -/
theorem chk_PL_last :
    (gPt (-123907047 / 64000000) (-1 / 256) 50).re.hi +
      max 0 (1 / 64 * (dirI (gPt (-123907047 / 64000000) (-1 / 256) 50) (-4092953 / 1000000)
          (1 / 4)).hi +
        g2Box (-2) (-123907047 / 64000000) (-1 / 256) 0 *
          ((-4092953 / 1000000) ^ 2 + (1 / 4) ^ 2) / 2 * (1 / 64) ^ 2) ≤ -2325535 / 10000 ∧
    (∀ bc ∈ famCB, 0 < lowN (bc.1 + -2) (bc.1 + -123907047 / 64000000) (-1 / 256) 0) ∧
    (gPt (-2) 0 50).re.hi ≤ -2325535 / 10000 := by
  decide +kernel

/-- The lower ray `20 - i [1/4, 162]` for `g`. -/
theorem chk_ray_G : chkSeg (fun x y => gPt x y 50) g2Box okBox 20 (-1 / 4) 0 (-647 / 4)
    (-2400670 / 10000)
    [mkRat 1 32, mkRat 1 16, mkRat 5 64, mkRat 3 32, mkRat 7 64, mkRat 15 128, mkRat 1 8,
      mkRat 17 128, mkRat 35 256, mkRat 9 64, mkRat 73 512, mkRat 37 256, mkRat 75 512,
      mkRat 151 1024, mkRat 19 128, mkRat 153 1024, mkRat 77 512, mkRat 39 256, mkRat 79 512,
      mkRat 81 512, mkRat 83 512, mkRat 87 512, mkRat 91 512, mkRat 99 512, mkRat 115 512,
      mkRat 131 512, mkRat 163 512, mkRat 227 512, mkRat 291 512, mkRat 803 1024] = true := by
  decide +kernel

/-- `Re e(20 - i/4)`. -/
theorem chk_ray_E : (ePt 20 (-1 / 4) 50).re.hi ≤ -97210 / 10000 := by
  decide +kernel

/-! ### Rectangles -/

theorem rect_BL (z : ℂ) (h1 : (2092953 / 1000000 : ℝ) ≤ z.re) (h2 : z.re ≤ 2702953 / 1000000)
    (h3 : -(523633 / 1000000 : ℝ) ≤ z.im) (h4 : z.im ≤ 0) :
    (famG z).re ≤ -2322435 / 10000 ∧ (famE z).re + 2 * Real.pi * z.im ≤ -93025 / 10000 := by
  constructor
  · have := chkRect_sound (gEvOK 50) gBoxOK chk_BL_G z (by push_cast; linarith)
      (by push_cast; linarith) (by push_cast; linarith) (by push_cast; linarith)
    push_cast at this
    linarith
  · have := chkRect_sound (esEvOK 50) esBoxOK chk_BL_E z (by push_cast; linarith)
      (by push_cast; linarith) (by push_cast; linarith) (by push_cast; linarith)
    rw [famEs_re] at this
    push_cast at this
    linarith

theorem rect_BR (z : ℂ) (h1 : (5604839 / 1000000 : ℝ) ≤ z.re) (h2 : z.re ≤ 20)
    (h3 : -(827198 / 1000000 : ℝ) ≤ z.im) (h4 : z.im ≤ 0) :
    (famG z).re ≤ -2321627 / 10000 ∧ (famE z).re + 2 * Real.pi * z.im ≤ -93914 / 10000 := by
  constructor
  · have := chkRect_sound (gEvOK 50) gBoxOK chk_BR_G z (by push_cast; linarith)
      (by push_cast; linarith) (by push_cast; linarith) (by push_cast; linarith)
    push_cast at this
    linarith
  · have := chkRect_sound (esEvOK 50) esBoxOK chk_BR_E z (by push_cast; linarith)
      (by push_cast; linarith) (by push_cast; linarith) (by push_cast; linarith)
    rw [famEs_re] at this
    push_cast at this
    linarith

/-! ### The segment `[P_L, -2]` -/

theorem seg_PL (θ : ℝ) (h0 : 0 ≤ θ) (h1 : θ ≤ 1) :
    (famG (cq (2092953 / 1000000) (-1 / 4) + θ * cq (-4092953 / 1000000) (1 / 4))).re ≤
        -2325535 / 10000 ∧
      (famE (cq (2092953 / 1000000) (-1 / 4) + θ * cq (-4092953 / 1000000) (1 / 4))).re +
        2 * Real.pi * (cq (2092953 / 1000000) (-1 / 4) + θ * cq (-4092953 / 1000000) (1 / 4)).im
        ≤ -91937 / 10000 := by
  obtain ⟨hlast, hpos, hend⟩ := chk_PL_last
  constructor
  · rcases le_or_gt θ (63 / 64) with hθ | hθ
    · -- the grid `[P_L, Q]`
      have k := chkSeg_sound (gEvOK 50) gBoxOK chk_PL_G (θ * (64 / 63)) (by positivity)
        (by linarith)
      have e : cq (2092953 / 1000000) (-1 / 4) + ((θ * (64 / 63) : ℝ) : ℂ) *
          cq (-257856039 / 64000000) (63 / 256) =
          cq (2092953 / 1000000) (-1 / 4) + θ * cq (-4092953 / 1000000) (1 / 4) := by
        apply Complex.ext <;> simp [cq] <;> ring
      rw [e] at k
      push_cast at k
      linarith
    rcases eq_or_lt_of_le h1 with h1 | h1
    · -- the end point `-2`
      subst h1
      have e : cq (2092953 / 1000000) (-1 / 4) + ((1 : ℝ) : ℂ) * cq (-4092953 / 1000000) (1 / 4) =
          cq (-2) 0 := by
        apply Complex.ext <;> norm_num [cq]
      rw [e]
      have k := (mem_gPt (-2) 0 50).1.2
      have hend' := (Rat.cast_le (K := ℝ)).2 hend
      push_cast at hend'
      linarith
    · -- the last piece `[Q, -2)`, one-sided from `Q`
      set qx : ℚ := -123907047 / 64000000
      set qy : ℚ := -1 / 256
      set ex : ℚ := -4092953 / 1000000
      set ey : ℚ := 1 / 4
      have e : cq (2092953 / 1000000) (-1 / 4) + θ * cq ex ey =
          cq qx qy + ((θ - 63 / 64 : ℝ) : ℂ) * cq ex ey := by
        apply Complex.ext <;> simp [cq, qx, qy, ex, ey] <;> ring
      rw [e]
      have hseg : ∀ z ∈ segment ℝ (cq qx qy) (cq qx qy + ((θ - 63 / 64 : ℝ) : ℂ) * cq ex ey),
          HasDerivAt famG (famG1 z) z ∧ HasDerivAt famG1 (famG2 z) z ∧
            ‖famG2 z‖ ≤ (g2Box (-2) qx qy 0 : ℝ) := by
        intro z hz
        obtain ⟨τ, k1, k2, rfl⟩ := mem_segment_line (A := cq qx qy) (e := cq ex ey) (τ₁ := 0)
          (τ₂ := θ - 63 / 64) (by simpa using hz)
        rw [min_eq_left (by linarith)] at k1
        rw [max_eq_right (by linarith)] at k2
        have hre : (cq qx qy + (τ : ℂ) * cq ex ey).re = qx + τ * ex := by simp
        have him : (cq qx qy + (τ : ℂ) * cq ex ey).im = qy + τ * ey := by simp
        have hqx : (qx : ℝ) = -123907047 / 64000000 := by norm_num [qx]
        have hqy : (qy : ℝ) = -1 / 256 := by norm_num [qy]
        have hex : (ex : ℝ) = -4092953 / 1000000 := by norm_num [ex]
        have hey : (ey : ℝ) = 1 / 4 := by norm_num [ey]
        have hslit : cq qx qy + (τ : ℂ) * cq ex ey ∈ slitPlane := by
          rw [mem_slitPlane_iff]
          right
          rw [him, hqy, hey]
          intro h
          linarith
        refine ⟨hasDerivAt_famG hslit, hasDerivAt_famG1 hslit, norm_famG2_le_box ?_ ?_ hpos⟩
        · rw [hre, hqx, hex]
          push_cast
          constructor <;> nlinarith
        · rw [him, hqy, hey]
          push_cast
          constructor <;> nlinarith
      have k := re_le_quad (Φ := famG) (Φ' := famG1) (Φ'' := famG2) (u := cq qx qy)
        (e := cq ex ey) (l := 1 / 64) (by linarith) (by linarith) (mem_gPt qx qy 50).1.2
        (mem_dirI (mem_gPt qx qy 50) ex ey).2 hseg
      have hnorm : ‖cq ex ey‖ ^ 2 = ((ex ^ 2 + ey ^ 2 : ℚ) : ℝ) := by
        rw [← normSq_eq_norm_sq, normSq_apply]; simp; ring
      rw [hnorm] at k
      have hlast' := (Rat.cast_le (K := ℝ)).2 hlast
      push_cast at hlast' k ⊢
      linarith
  · have k := chkSeg_sound (esEvOK 50) esBoxOK chk_PL_E θ h0 h1
    rw [famEs_re] at k
    push_cast at k
    linarith

/-! ### The lower ray `{20 - i y : y ≥ 1/4}` -/

/-- `s - s³/3 ≤ arctan s` for `s ≥ 0`. -/
theorem sub_cube_le_arctan {s : ℝ} (hs : 0 ≤ s) : s - s ^ 3 / 3 ≤ Real.arctan s := by
  have hd : ∀ t : ℝ, HasDerivAt (fun t => Real.arctan t - t + t ^ 3 / 3)
      (1 / (1 + t ^ 2) - 1 + t ^ 2) t := by
    intro t
    have h := ((Real.hasDerivAt_arctan t).sub (hasDerivAt_id' t)).add
      ((hasDerivAt_pow 3 t).div_const 3)
    exact h.congr_deriv (by rw [show (3 : ℕ) - 1 = 2 from rfl]; push_cast; ring)
  have hmono : Monotone (fun t => Real.arctan t - t + t ^ 3 / 3) := by
    refine monotone_of_deriv_nonneg (fun t => (hd t).differentiableAt) fun t => ?_
    rw [(hd t).deriv]
    have h1 : 0 < 1 + t ^ 2 := by positivity
    have : 1 / (1 + t ^ 2) - 1 + t ^ 2 = t ^ 4 / (1 + t ^ 2) := by
      field_simp
      ring
    rw [this]
    positivity
  have := hmono hs
  simp only [Real.arctan_zero, sub_zero, ne_eq, OfNat.ofNat_ne_zero,
    not_false_eq_true, zero_pow, zero_div, add_zero] at this
  linarith

/-- `Im log (b + x - i y) = arctan ((b + x) / y) - π / 2` for `b + x, y > 0`. -/
theorem im_log_ray {b x y : ℝ} (hbx : 0 < b + x) (hy : 0 < y) :
    (log ((b : ℂ) + ((x : ℂ) - (y : ℂ) * I))).im = Real.arctan ((b + x) / y) - Real.pi / 2 := by
  rw [log_im]
  have e : (b : ℂ) + ((x : ℂ) - (y : ℂ) * I) = ((b + x : ℝ) : ℂ) + ((-y : ℝ) : ℂ) * I := by
    push_cast; ring
  rw [e, Num.arg_of_re_pos' hbx, neg_div, Real.arctan_neg]
  have := Real.arctan_inv_of_pos (x := (b + x) / y) (by positivity)
  rw [inv_div] at this
  linarith

theorem arctan_div_le (k : ℝ) (hk : 0 ≤ k) {y : ℝ} (hy : 0 < y) :
    Real.arctan (k / y) ≤ k * y⁻¹ := by
  rw [div_eq_mul_inv]
  exact Real.arctan_le_self (by positivity)

theorem le_arctan_div (k : ℝ) (hk : 0 ≤ k) {y : ℝ} (hy : 0 < y) :
    k * y⁻¹ - k ^ 3 / 3 * y⁻¹ ^ 3 ≤ Real.arctan (k / y) := by
  rw [div_eq_mul_inv k y]
  have := sub_cube_le_arctan (s := k * y⁻¹) (by positivity)
  rw [mul_pow] at this
  linarith

/-- **Lemma 8.6(ii)** at `x = 20`: `d/dy Re g(20 - i y) = Im g'(20 - i y) ≤ 0` for `y ≥ 162`. -/
theorem im_famG1_ray_nonpos {y : ℝ} (hy : 162 ≤ y) : (famG1 ((20 : ℝ) - y * I)).im ≤ 0 := by
  have hy0 : 0 < y := by linarith
  have key : ∀ bc : ℕ × ℤ, ((bc.2 : ℂ) * log ((bc.1 : ℂ) + ((20 : ℝ) - (y : ℂ) * I))).im =
      bc.2 * (Real.arctan ((bc.1 + 20) / y) - Real.pi / 2) := by
    intro bc
    rw [intCast_eq_ofReal, im_ofReal_mul, ← Complex.ofReal_natCast,
      im_log_ray (by positivity) hy0]
  unfold famG1
  rw [im_list_sum]
  simp only [key]
  simp only [famCB, List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
  norm_num
  set v := y⁻¹ with hv
  have hv0 : 0 < v := inv_pos.2 hy0
  have hv1 : v ≤ 1 / 162 := by rw [hv, one_div]; exact inv_anti₀ (by norm_num) hy
  have hv2 : v ^ 2 ≤ 1 / 26244 := by
    have := pow_le_pow_left₀ hv0.le hv1 2
    norm_num at this ⊢
    linarith
  have hv3 : v ^ 3 ≤ v * (1 / 26244) := by
    rw [pow_succ']
    exact mul_le_mul_of_nonneg_left hv2 hv0.le
  linarith [arctan_div_le 170 (by norm_num) hy0, arctan_div_le 65 (by norm_num) hy0,
    arctan_div_le 68 (by norm_num) hy0, arctan_div_le 70 (by norm_num) hy0,
    arctan_div_le 73 (by norm_num) hy0, arctan_div_le 76 (by norm_num) hy0,
    arctan_div_le 80 (by norm_num) hy0, le_arctan_div 20 (by norm_num) hy0,
    le_arctan_div 125 (by norm_num) hy0, le_arctan_div 122 (by norm_num) hy0,
    le_arctan_div 120 (by norm_num) hy0, le_arctan_div 117 (by norm_num) hy0,
    le_arctan_div 114 (by norm_num) hy0, le_arctan_div 110 (by norm_num) hy0]

/-- `d/dy Re e(20 - i y) = arctan (94 / y) - arctan (96 / y) ≤ 0`. -/
theorem im_famE1_ray_nonpos {y : ℝ} (hy : 0 < y) : (famE1 ((20 : ℝ) - y * I)).im ≤ 0 := by
  unfold famE1
  rw [sub_im, show (74 : ℂ) = ((74 : ℝ) : ℂ) by norm_num,
    show (76 : ℂ) = ((76 : ℝ) : ℂ) by norm_num, im_log_ray (by norm_num) hy,
    im_log_ray (by norm_num) hy]
  have := Real.arctan_strictMono.monotone
    (show (74 + 20 : ℝ) / y ≤ (76 + 20) / y by gcongr; norm_num)
  linarith

theorem ray_mem_slitPlane (y : ℝ) : ((20 : ℝ) : ℂ) - (y : ℂ) * I ∈ slitPlane := by
  rw [mem_slitPlane_iff]
  left
  simp

theorem ray_bound (y : ℝ) (hy : 1 / 4 ≤ y) :
    (famG ((20 : ℝ) - y * I)).re ≤ -2400670 / 10000 ∧
      (famE ((20 : ℝ) - y * I)).re ≤ -97210 / 10000 := by
  have hseg : ∀ y : ℝ, 1 / 4 ≤ y → y ≤ 162 → (famG ((20 : ℝ) - y * I)).re ≤ -2400670 / 10000 := by
    intro y h1 h2
    have k := chkSeg_sound (gEvOK 50) gBoxOK chk_ray_G ((y - 1 / 4) / (647 / 4))
      (div_nonneg (by linarith) (by norm_num)) ((div_le_one (by norm_num)).2 (by linarith))
    have e : cq 20 (-1 / 4) + (((y - 1 / 4) / (647 / 4) : ℝ) : ℂ) * cq 0 (-647 / 4) =
        ((20 : ℝ) : ℂ) - (y : ℂ) * I := by
      apply Complex.ext <;>
        simp only [cq_re, cq_im, add_re, add_im, mul_re, mul_im, ofReal_re, ofReal_im, sub_re,
          sub_im, I_re, I_im] <;> push_cast <;> ring
    rw [e] at k
    push_cast at k ⊢
    linarith
  constructor
  · rcases le_total y 162 with h | h
    · exact hseg y hy h
    · refine (re_antitone_ray (Φ := famG) (Φ' := famG1) (x := 20) (y₀ := 162) ?_ ?_ h).trans
        (hseg 162 (by norm_num) le_rfl)
      · intro y _
        exact hasDerivAt_famG (ray_mem_slitPlane y)
      · intro y hy
        exact im_famG1_ray_nonpos hy.le
  · have h74 : ∀ y : ℝ, (74 : ℂ) + (((20 : ℝ) : ℂ) - (y : ℂ) * I) ∈ slitPlane := by
      intro y
      have := add_mem_slitPlane (ray_mem_slitPlane y) (a := 74) (by norm_num)
      simpa using this
    have h76 : ∀ y : ℝ, (76 : ℂ) + (((20 : ℝ) : ℂ) - (y : ℂ) * I) ∈ slitPlane := by
      intro y
      have := add_mem_slitPlane (ray_mem_slitPlane y) (a := 76) (by norm_num)
      simpa using this
    refine (re_antitone_ray (Φ := famE) (Φ' := famE1) (x := 20) (y₀ := 1 / 4) ?_ ?_ hy).trans ?_
    · intro y _
      exact hasDerivAt_famE (h74 y) (h76 y)
    · intro y hy
      exact im_famE1_ray_nonpos (by linarith)
    · have k := (mem_ePt 20 (-1 / 4) 50).1.2
      have e : cq 20 (-1 / 4) = ((20 : ℝ) : ℂ) - ((1 / 4 : ℝ) : ℂ) * I := by
        apply Complex.ext <;> norm_num [cq]
      rw [e] at k
      have k2 := (Rat.cast_le (K := ℝ)).2 chk_ray_E
      push_cast at k2
      linarith

end OddZeta.FamNum
