import OddZeta.Family.SmallMach

/-!
# Per-`r` certificate data and kernel checks, chunk 4: `r ∈ {93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121}`

Generated by `scripts/small_cert_gen.py`.
-/

set_option linter.style.longLine false

namespace OddZeta.Small

/-- The certificate data for `r = 93`. -/
def d93 : SmData where
  ur := mkRat (417096645790201) 100000000000000
  ui := mkRat (-7349371681599) 20000000000000
  vr := mkRat (-749) 500
  vi := mkRat (21) 250
  V := mkRat (750177) 500000
  m := mkRat (341811) 20000
  M3 := mkRat (3322673) 250000
  b := mkRat (1) 100
  T := mkRat (-10795427) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2834483) 500000
  bi := mkRat (-451469) 1000000
  tr := mkRat (1336483) 500000
  ti := mkRat (-283469) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (336483) 1000000
  ply := mkRat (-70867) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (12097) 100000
  na := mkRat (-60549) 1000000
  nb := mkRat (-199633) 200000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 95`. -/
def d95 : SmData where
  ur := mkRat (13037029349091) 3125000000000
  ui := mkRat (-17988933926501) 50000000000000
  vr := mkRat (-749) 500
  vi := mkRat (41) 500
  V := mkRat (1500243) 1000000
  m := mkRat (3491237) 200000
  M3 := mkRat (13566589) 1000000
  b := mkRat (1) 100
  T := mkRat (-22054921) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5669849) 1000000
  bi := mkRat (-441779) 1000000
  tr := mkRat (2673849) 1000000
  ti := mkRat (-277779) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (13477) 40000
  ply := mkRat (-13889) 100000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (11853) 100000
  na := mkRat (-927) 15625
  nb := mkRat (-499119) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 97`. -/
def d97 : SmData where
  ur := mkRat (417267909333593) 100000000000000
  ui := mkRat (-2202519893057) 6250000000000
  vr := mkRat (-749) 500
  vi := mkRat (2) 25
  V := mkRat (300027) 200000
  m := mkRat (3564371) 200000
  M3 := mkRat (13842651) 1000000
  b := mkRat (1) 100
  T := mkRat (-22518989) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5670679) 1000000
  bi := mkRat (-432403) 1000000
  tr := mkRat (2674679) 1000000
  ti := mkRat (-272403) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (337339) 1000000
  ply := mkRat (-68101) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (5811) 50000
  na := mkRat (-58173) 1000000
  nb := mkRat (-499153) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 99`. -/
def d99 : SmData where
  ur := mkRat (208672988860447) 50000000000000
  ui := mkRat (-34532325006487) 100000000000000
  vr := mkRat (-749) 500
  vi := mkRat (79) 1000
  V := mkRat (750041) 500000
  m := mkRat (18187559) 1000000
  M3 := mkRat (14119409) 1000000
  b := mkRat (1) 100
  T := mkRat (-22983057) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (283573) 50000
  bi := mkRat (-424323) 1000000
  tr := mkRat (133773) 50000
  ti := mkRat (-266323) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (33773) 100000
  ply := mkRat (-66581) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (5681) 50000
  na := mkRat (-56869) 1000000
  nb := mkRat (-998381) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 101`. -/
def d101 : SmData where
  ur := mkRat (208709762410303) 50000000000000
  ui := mkRat (-16926075303501) 50000000000000
  vr := mkRat (-749) 500
  vi := mkRat (77) 1000
  V := mkRat (749989) 500000
  m := mkRat (9276647) 500000
  M3 := mkRat (3598941) 250000
  b := mkRat (1) 100
  T := mkRat (-23447127) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1134439) 200000
  bi := mkRat (-207761) 500000
  tr := mkRat (535239) 200000
  ti := mkRat (-130761) 500000
  rs := mkRat (1) 500000
  plx := mkRat (338097) 1000000
  ply := mkRat (-130761) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (2789) 25000
  na := mkRat (-27919) 500000
  nb := mkRat (-998439) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 103`. -/
def d103 : SmData where
  ur := mkRat (417488894851981) 100000000000000
  ui := mkRat (-16599095460493) 50000000000000
  vr := mkRat (-749) 500
  vi := mkRat (3) 40
  V := mkRat (1499877) 1000000
  m := mkRat (9459529) 500000
  M3 := mkRat (7336129) 500000
  b := mkRat (1) 100
  T := mkRat (-23911197) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5672889) 1000000
  bi := mkRat (-203491) 500000
  tr := mkRat (2676889) 1000000
  ti := mkRat (-128491) 500000
  rs := mkRat (1) 500000
  plx := mkRat (67689) 200000
  ply := mkRat (-128491) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (10961) 100000
  na := mkRat (-3429) 62500
  nb := mkRat (-998493) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 105`. -/
def d105 : SmData where
  ur := mkRat (417554399838231) 100000000000000
  ui := mkRat (-814224062699) 2500000000000
  vr := mkRat (-749) 500
  vi := mkRat (37) 500
  V := mkRat (1499827) 1000000
  m := mkRat (385697) 20000
  M3 := mkRat (14949411) 1000000
  b := mkRat (1) 100
  T := mkRat (-6093817) 250
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (709193) 125000
  bi := mkRat (-39969) 100000
  tr := mkRat (334693) 125000
  ti := mkRat (-25169) 100000
  rs := mkRat (1) 500000
  plx := mkRat (84693) 250000
  ply := mkRat (-25169) 200000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (2147) 20000
  na := mkRat (-5373) 100000
  nb := mkRat (-199711) 200000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 107`. -/
def d107 : SmData where
  ur := mkRat (83523264631073) 20000000000000
  ui := mkRat (-3995386441797) 12500000000000
  vr := mkRat (-749) 500
  vi := mkRat (73) 1000
  V := mkRat (749889) 500000
  m := mkRat (19650669) 1000000
  M3 := mkRat (15226687) 1000000
  b := mkRat (1) 100
  T := mkRat (-1241967) 50
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5674163) 1000000
  bi := mkRat (-392631) 1000000
  tr := mkRat (2678163) 1000000
  ti := mkRat (-246631) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (169541) 500000
  ply := mkRat (-30829) 250000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (5259) 50000
  na := mkRat (-26323) 500000
  nb := mkRat (-998613) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 109`. -/
def d109 : SmData where
  ur := mkRat (52209365329113) 12500000000000
  ui := mkRat (-31379303856099) 100000000000000
  vr := mkRat (-749) 500
  vi := mkRat (71) 1000
  V := mkRat (749841) 500000
  m := mkRat (312758) 15625
  M3 := mkRat (15503533) 1000000
  b := mkRat (1) 100
  T := mkRat (-25303413) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5674749) 1000000
  bi := mkRat (-384793) 1000000
  tr := mkRat (2678749) 1000000
  ti := mkRat (-242793) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (169687) 500000
  ply := mkRat (-30349) 250000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (5177) 50000
  na := mkRat (-25911) 500000
  nb := mkRat (-15604) 15625
  K := mkRat (80001) 1000

/-- The certificate data for `r = 111`. -/
def d111 : SmData where
  ur := mkRat (41773043327) 10000000000
  ui := mkRat (-15408208078133) 50000000000000
  vr := mkRat (-749) 500
  vi := mkRat (7) 100
  V := mkRat (299927) 200000
  m := mkRat (20382379) 1000000
  M3 := mkRat (631241) 40000
  b := mkRat (1) 100
  T := mkRat (-12883743) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (709413) 125000
  bi := mkRat (-94541) 250000
  tr := mkRat (334913) 125000
  ti := mkRat (-59541) 250000
  rs := mkRat (1) 500000
  plx := mkRat (84913) 250000
  ply := mkRat (-59541) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (2539) 25000
  na := mkRat (-50831) 1000000
  nb := mkRat (-998707) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 113`. -/
def d113 : SmData where
  ur := mkRat (417783069620483) 100000000000000
  ui := mkRat (-6054665602011) 20000000000000
  vr := mkRat (-749) 500
  vi := mkRat (69) 1000
  V := mkRat (1499589) 1000000
  m := mkRat (5187067) 250000
  M3 := mkRat (802931) 50000
  b := mkRat (1) 100
  T := mkRat (-655789) 25
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5675831) 1000000
  bi := mkRat (-371733) 1000000
  tr := mkRat (2679831) 1000000
  ti := mkRat (-233733) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (84979) 250000
  ply := mkRat (-58433) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4983) 50000
  na := mkRat (-24941) 500000
  nb := mkRat (-199751) 200000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 115`. -/
def d115 : SmData where
  ur := mkRat (417833027892191) 100000000000000
  ui := mkRat (-29749014765443) 100000000000000
  vr := mkRat (-749) 500
  vi := mkRat (17) 250
  V := mkRat (1499543) 1000000
  m := mkRat (10557089) 500000
  M3 := mkRat (8168151) 500000
  b := mkRat (1) 100
  T := mkRat (-13347817) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (567633) 100000
  bi := mkRat (-36549) 100000
  tr := mkRat (268033) 100000
  ti := mkRat (-22949) 100000
  rs := mkRat (1) 500000
  plx := mkRat (68033) 200000
  ply := mkRat (-22949) 200000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (1957) 20000
  na := mkRat (-24487) 500000
  nb := mkRat (-2497) 2500
  K := mkRat (80001) 1000

/-- The certificate data for `r = 117`. -/
def d117 : SmData where
  ur := mkRat (104470121949753) 25000000000000
  ui := mkRat (-7310630285971) 25000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (33) 500
  V := mkRat (1500453) 1000000
  m := mkRat (5370027) 250000
  M3 := mkRat (1039107) 62500
  b := mkRat (1) 100
  T := mkRat (-27159709) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1135561) 200000
  bi := mkRat (-14337) 40000
  tr := mkRat (535961) 200000
  ti := mkRat (-9057) 40000
  rs := mkRat (1) 500000
  plx := mkRat (169951) 500000
  ply := mkRat (-28303) 250000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (1931) 20000
  na := mkRat (-24163) 500000
  nb := mkRat (-998831) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 119`. -/
def d119 : SmData where
  ur := mkRat (417925614198377) 100000000000000
  ui := mkRat (-7188238869389) 25000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (13) 200
  V := mkRat (1500409) 1000000
  m := mkRat (21846057) 1000000
  M3 := mkRat (2112971) 125000
  b := mkRat (1) 100
  T := mkRat (-5524757) 200
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (354891) 62500
  bi := mkRat (-35253) 100000
  tr := mkRat (41879) 15625
  ti := mkRat (-22253) 100000
  rs := mkRat (1) 500000
  plx := mkRat (10629) 31250
  ply := mkRat (-22253) 200000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (593) 6250
  na := mkRat (-11873) 250000
  nb := mkRat (-998871) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 121`. -/
def d121 : SmData where
  ur := mkRat (104492139635539) 25000000000000
  ui := mkRat (-14139742255317) 50000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (8) 125
  V := mkRat (750183) 500000
  m := mkRat (2776503) 125000
  M3 := mkRat (17181909) 1000000
  b := mkRat (1) 100
  T := mkRat (-28087861) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2839343) 500000
  bi := mkRat (-69359) 200000
  tr := mkRat (1340343) 500000
  ti := mkRat (-43759) 200000
  rs := mkRat (1) 500000
  plx := mkRat (340343) 1000000
  ply := mkRat (-54699) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (9329) 100000
  na := mkRat (-46693) 1000000
  nb := mkRat (-998909) 1000000
  K := mkRat (80001) 1000

theorem ok93 : famCertOK 93 d93 = true := by
  decide +kernel

theorem ok95 : famCertOK 95 d95 = true := by
  decide +kernel

theorem ok97 : famCertOK 97 d97 = true := by
  decide +kernel

theorem ok99 : famCertOK 99 d99 = true := by
  decide +kernel

theorem ok101 : famCertOK 101 d101 = true := by
  decide +kernel

theorem ok103 : famCertOK 103 d103 = true := by
  decide +kernel

theorem ok105 : famCertOK 105 d105 = true := by
  decide +kernel

theorem ok107 : famCertOK 107 d107 = true := by
  decide +kernel

theorem ok109 : famCertOK 109 d109 = true := by
  decide +kernel

theorem ok111 : famCertOK 111 d111 = true := by
  decide +kernel

theorem ok113 : famCertOK 113 d113 = true := by
  decide +kernel

theorem ok115 : famCertOK 115 d115 = true := by
  decide +kernel

theorem ok117 : famCertOK 117 d117 = true := by
  decide +kernel

theorem ok119 : famCertOK 119 d119 = true := by
  decide +kernel

theorem ok121 : famCertOK 121 d121 = true := by
  decide +kernel

/-- The data of chunk 4. -/
def chunk4 : List (ℕ × SmData) :=
  [(93, d93), (95, d95), (97, d97), (99, d99), (101, d101), (103, d103), (105, d105), (107, d107), (109, d109), (111, d111), (113, d113), (115, d115), (117, d117), (119, d119), (121, d121)]

theorem chunk4_ok : ∀ p ∈ chunk4, famCertOK p.1 p.2 = true :=
  List.forall_mem_cons.2 ⟨ok93,
    List.forall_mem_cons.2 ⟨ok95,
    List.forall_mem_cons.2 ⟨ok97,
    List.forall_mem_cons.2 ⟨ok99,
    List.forall_mem_cons.2 ⟨ok101,
    List.forall_mem_cons.2 ⟨ok103,
    List.forall_mem_cons.2 ⟨ok105,
    List.forall_mem_cons.2 ⟨ok107,
    List.forall_mem_cons.2 ⟨ok109,
    List.forall_mem_cons.2 ⟨ok111,
    List.forall_mem_cons.2 ⟨ok113,
    List.forall_mem_cons.2 ⟨ok115,
    List.forall_mem_cons.2 ⟨ok117,
    List.forall_mem_cons.2 ⟨ok119,
    List.forall_mem_cons.2 ⟨ok121,
    List.forall_mem_nil _⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩

end OddZeta.Small
