import OddZeta.Family.SmallMach

/-!
# Per-`r` certificate data and kernel checks, chunk 6: `r ∈ {153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181}`

Generated by `scripts/small_cert_gen.py`.
-/

set_option linter.style.longLine false

namespace OddZeta.Small

/-- The certificate data for `r = 153`. -/
def d153 : SmData where
  ur := mkRat (209223054634177) 50000000000000
  ui := mkRat (-11190300717493) 50000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (51) 1000
  V := mkRat (374967) 250000
  m := mkRat (1403469) 50000
  M3 := mkRat (10821037) 500000
  b := mkRat (1) 100
  T := mkRat (-35513131) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5683461) 1000000
  bi := mkRat (-137403) 500000
  tr := mkRat (2685461) 1000000
  ti := mkRat (-86403) 500000
  rs := mkRat (1) 500000
  plx := mkRat (342731) 1000000
  ply := mkRat (-86403) 1000000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (7363) 100000
  na := mkRat (-4607) 125000
  nb := mkRat (-24983) 25000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 155`. -/
def d155 : SmData where
  ur := mkRat (52308338942711) 12500000000000
  ui := mkRat (-883699840557) 4000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (1) 20
  V := mkRat (749917) 500000
  m := mkRat (5687111) 200000
  M3 := mkRat (5480281) 250000
  b := mkRat (1) 100
  T := mkRat (-8994303) 250
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5683667) 1000000
  bi := mkRat (-10837) 40000
  tr := mkRat (2685667) 1000000
  ti := mkRat (-6837) 40000
  rs := mkRat (1) 500000
  plx := mkRat (171417) 500000
  ply := mkRat (-42731) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (7283) 100000
  na := mkRat (-36453) 1000000
  nb := mkRat (-199867) 200000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 157`. -/
def d157 : SmData where
  ur := mkRat (418486547110479) 100000000000000
  ui := mkRat (-21811706454131) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (1) 20
  V := mkRat (749917) 500000
  m := mkRat (14400869) 500000
  M3 := mkRat (1387547) 62500
  b := mkRat (1) 100
  T := mkRat (-7288259) 200
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1136773) 200000
  bi := mkRat (-268117) 1000000
  tr := mkRat (537173) 200000
  ti := mkRat (-168117) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (342933) 1000000
  ply := mkRat (-42029) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (7163) 100000
  na := mkRat (-17927) 500000
  nb := mkRat (-999357) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 159`. -/
def d159 : SmData where
  ur := mkRat (418505653878771) 100000000000000
  ui := mkRat (-21537957865191) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (49) 1000
  V := mkRat (1499801) 1000000
  m := mkRat (29167929) 1000000
  M3 := mkRat (5619969) 250000
  b := mkRat (1) 100
  T := mkRat (-36905377) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5684057) 1000000
  bi := mkRat (-13219) 50000
  tr := mkRat (2686057) 1000000
  ti := mkRat (-8319) 50000
  rs := mkRat (1) 500000
  plx := mkRat (85757) 250000
  ply := mkRat (-8319) 100000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (7089) 100000
  na := mkRat (-17741) 500000
  nb := mkRat (-99937) 100000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 161`. -/
def d161 : SmData where
  ur := mkRat (26157754214323) 6250000000000
  ui := mkRat (-4254197788983) 20000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (6) 125
  V := mkRat (1499769) 1000000
  m := mkRat (1845883) 62500
  M3 := mkRat (22759041) 1000000
  b := mkRat (1) 100
  T := mkRat (-1868473) 50
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5684241) 1000000
  bi := mkRat (-26071) 100000
  tr := mkRat (2686241) 1000000
  ti := mkRat (-16471) 100000
  rs := mkRat (1) 500000
  plx := mkRat (4289) 12500
  ply := mkRat (-16471) 200000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (7017) 100000
  na := mkRat (-281) 8000
  nb := mkRat (-499691) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 163`. -/
def d163 : SmData where
  ur := mkRat (10463545529791) 2500000000000
  ui := mkRat (-21010551150771) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (6) 125
  V := mkRat (1499769) 1000000
  m := mkRat (14950167) 500000
  M3 := mkRat (23038767) 1000000
  b := mkRat (1) 100
  T := mkRat (-18916771) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2842209) 500000
  bi := mkRat (-129053) 500000
  tr := mkRat (1343209) 500000
  ti := mkRat (-81053) 500000
  rs := mkRat (1) 500000
  plx := mkRat (343209) 1000000
  ply := mkRat (-81053) 1000000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (3453) 50000
  na := mkRat (-34569) 1000000
  nb := mkRat (-499701) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 165`. -/
def d165 : SmData where
  ur := mkRat (5231986832477) 1250000000000
  ui := mkRat (-2075640793117) 10000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (47) 1000
  V := mkRat (1499737) 1000000
  m := mkRat (30266547) 1000000
  M3 := mkRat (11658991) 500000
  b := mkRat (1) 100
  T := mkRat (-306381) 8
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5684589) 1000000
  bi := mkRat (-63641) 250000
  tr := mkRat (2686589) 1000000
  ti := mkRat (-40141) 250000
  rs := mkRat (1) 500000
  plx := mkRat (68659) 200000
  ply := mkRat (-40141) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (6841) 100000
  na := mkRat (-107) 3125
  nb := mkRat (-999413) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 167`. -/
def d167 : SmData where
  ur := mkRat (209287736612269) 50000000000000
  ui := mkRat (-4101666802321) 20000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (47) 1000
  V := mkRat (1499737) 1000000
  m := mkRat (30632767) 1000000
  M3 := mkRat (23597769) 1000000
  b := mkRat (1) 100
  T := mkRat (-9690427) 250
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1136951) 200000
  bi := mkRat (-252083) 1000000
  tr := mkRat (537351) 200000
  ti := mkRat (-158083) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (343377) 1000000
  ply := mkRat (-39521) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (1347) 20000
  na := mkRat (-3371) 100000
  nb := mkRat (-999431) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 169`. -/
def d169 : SmData where
  ur := mkRat (418591428920623) 100000000000000
  ui := mkRat (-20266114731149) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (23) 500
  V := mkRat (749853) 500000
  m := mkRat (15499497) 500000
  M3 := mkRat (23877047) 1000000
  b := mkRat (1) 100
  T := mkRat (-4903224) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2842457) 500000
  bi := mkRat (-248661) 1000000
  tr := mkRat (1343457) 500000
  ti := mkRat (-156661) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (343457) 1000000
  ply := mkRat (-7833) 100000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (3337) 50000
  na := mkRat (-16703) 500000
  nb := mkRat (-999441) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 171`. -/
def d171 : SmData where
  ur := mkRat (209303419964987) 50000000000000
  ui := mkRat (-10014772712601) 50000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (9) 200
  V := mkRat (374919) 250000
  m := mkRat (15682613) 500000
  M3 := mkRat (24156361) 1000000
  b := mkRat (1) 100
  T := mkRat (-317519) 8
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1421267) 250000
  bi := mkRat (-49059) 200000
  tr := mkRat (671767) 250000
  ti := mkRat (-31059) 200000
  rs := mkRat (1) 500000
  plx := mkRat (171767) 500000
  ply := mkRat (-4853) 62500
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (827) 12500
  na := mkRat (-16557) 500000
  nb := mkRat (-999451) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 173`. -/
def d173 : SmData where
  ur := mkRat (418621730999949) 100000000000000
  ui := mkRat (-19798430850801) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (9) 200
  V := mkRat (374919) 250000
  m := mkRat (6346293) 200000
  M3 := mkRat (6109057) 250000
  b := mkRat (1) 100
  T := mkRat (-40153959) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5685217) 1000000
  bi := mkRat (-30373) 125000
  tr := mkRat (2687217) 1000000
  ti := mkRat (-19123) 125000
  rs := mkRat (1) 500000
  plx := mkRat (42951) 125000
  ply := mkRat (-19123) 250000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (6517) 100000
  na := mkRat (-32621) 1000000
  nb := mkRat (-999467) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 175`. -/
def d175 : SmData where
  ur := mkRat (418636125483087) 100000000000000
  ui := mkRat (-9786292325537) 50000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (11) 250
  V := mkRat (749823) 500000
  m := mkRat (3209771) 100000
  M3 := mkRat (24715581) 1000000
  b := mkRat (1) 100
  T := mkRat (-40618043) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5685361) 1000000
  bi := mkRat (-119863) 500000
  tr := mkRat (2687361) 1000000
  ti := mkRat (-75863) 500000
  rs := mkRat (1) 500000
  plx := mkRat (343681) 1000000
  ply := mkRat (-75863) 1000000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (6463) 100000
  na := mkRat (-1011) 31250
  nb := mkRat (-249869) 250000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 177`. -/
def d177 : SmData where
  ur := mkRat (52331255678819) 12500000000000
  ui := mkRat (-19351828855797) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (11) 250
  V := mkRat (749823) 500000
  m := mkRat (32463961) 1000000
  M3 := mkRat (12497749) 500000
  b := mkRat (1) 100
  T := mkRat (-41082127) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (11371) 2000
  bi := mkRat (-118759) 500000
  tr := mkRat (43) 16
  ti := mkRat (-74759) 500000
  rs := mkRat (1) 500000
  plx := mkRat (11) 32
  ply := mkRat (-74759) 1000000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (6369) 100000
  na := mkRat (-797) 25000
  nb := mkRat (-999491) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 179`. -/
def d179 : SmData where
  ur := mkRat (418663511678353) 100000000000000
  ui := mkRat (-1913599341523) 10000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (43) 1000
  V := mkRat (1499617) 1000000
  m := mkRat (32830217) 1000000
  M3 := mkRat (25274907) 1000000
  b := mkRat (1) 100
  T := mkRat (-41546211) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1137127) 200000
  bi := mkRat (-5859) 25000
  tr := mkRat (537527) 200000
  ti := mkRat (-3709) 25000
  rs := mkRat (1) 500000
  plx := mkRat (171909) 500000
  ply := mkRat (-3709) 50000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (79) 1250
  na := mkRat (-31633) 1000000
  nb := mkRat (-999499) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 181`. -/
def d181 : SmData where
  ur := mkRat (418676543926969) 100000000000000
  ui := mkRat (-18924915764683) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (43) 1000
  V := mkRat (1499617) 1000000
  m := mkRat (16598239) 500000
  M3 := mkRat (2555487) 100000
  b := mkRat (1) 100
  T := mkRat (-8402059) 200
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1137153) 200000
  bi := mkRat (-232249) 1000000
  tr := mkRat (537553) 200000
  ti := mkRat (-146249) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (343883) 1000000
  ply := mkRat (-18281) 250000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (623) 10000
  na := mkRat (-15591) 500000
  nb := mkRat (-999513) 1000000
  K := mkRat (80001) 1000

theorem ok153 : famCertOK 153 d153 = true := by
  decide +kernel

theorem ok155 : famCertOK 155 d155 = true := by
  decide +kernel

theorem ok157 : famCertOK 157 d157 = true := by
  decide +kernel

theorem ok159 : famCertOK 159 d159 = true := by
  decide +kernel

theorem ok161 : famCertOK 161 d161 = true := by
  decide +kernel

theorem ok163 : famCertOK 163 d163 = true := by
  decide +kernel

theorem ok165 : famCertOK 165 d165 = true := by
  decide +kernel

theorem ok167 : famCertOK 167 d167 = true := by
  decide +kernel

theorem ok169 : famCertOK 169 d169 = true := by
  decide +kernel

theorem ok171 : famCertOK 171 d171 = true := by
  decide +kernel

theorem ok173 : famCertOK 173 d173 = true := by
  decide +kernel

theorem ok175 : famCertOK 175 d175 = true := by
  decide +kernel

theorem ok177 : famCertOK 177 d177 = true := by
  decide +kernel

theorem ok179 : famCertOK 179 d179 = true := by
  decide +kernel

theorem ok181 : famCertOK 181 d181 = true := by
  decide +kernel

/-- The data of chunk 6. -/
def chunk6 : List (ℕ × SmData) :=
  [(153, d153), (155, d155), (157, d157), (159, d159), (161, d161), (163, d163), (165, d165), (167, d167), (169, d169), (171, d171), (173, d173), (175, d175), (177, d177), (179, d179), (181, d181)]

theorem chunk6_ok : ∀ p ∈ chunk6, famCertOK p.1 p.2 = true :=
  List.forall_mem_cons.2 ⟨ok153,
    List.forall_mem_cons.2 ⟨ok155,
    List.forall_mem_cons.2 ⟨ok157,
    List.forall_mem_cons.2 ⟨ok159,
    List.forall_mem_cons.2 ⟨ok161,
    List.forall_mem_cons.2 ⟨ok163,
    List.forall_mem_cons.2 ⟨ok165,
    List.forall_mem_cons.2 ⟨ok167,
    List.forall_mem_cons.2 ⟨ok169,
    List.forall_mem_cons.2 ⟨ok171,
    List.forall_mem_cons.2 ⟨ok173,
    List.forall_mem_cons.2 ⟨ok175,
    List.forall_mem_cons.2 ⟨ok177,
    List.forall_mem_cons.2 ⟨ok179,
    List.forall_mem_cons.2 ⟨ok181,
    List.forall_mem_nil _⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩

end OddZeta.Small
