import OddZeta.Family.SmallMach

/-!
# Per-`r` certificate data and kernel checks, chunk 3: `r ∈ {63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91}`

Generated by `scripts/small_cert_gen.py`.
-/

set_option linter.style.longLine false

namespace OddZeta.Small

/-- The certificate data for `r = 63`. -/
def d63 : SmData where
  ur := mkRat (414624157527521) 100000000000000
  ui := mkRat (-13512853662827) 25000000000000
  vr := mkRat (-299) 200
  vi := mkRat (123) 1000
  V := mkRat (375013) 250000
  m := mkRat (11612547) 1000000
  M3 := mkRat (9167421) 1000000
  b := mkRat (1) 100
  T := mkRat (-14630037) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2820621) 500000
  bi := mkRat (-331757) 500000
  tr := mkRat (1325621) 500000
  ti := mkRat (-208757) 500000
  rs := mkRat (1) 500000
  plx := mkRat (325621) 1000000
  ply := mkRat (-208757) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (8931) 50000
  na := mkRat (-22351) 250000
  nb := mkRat (-199199) 200000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 65`. -/
def d65 : SmData where
  ur := mkRat (414899024821563) 100000000000000
  ui := mkRat (-52409095989947) 100000000000000
  vr := mkRat (-299) 200
  vi := mkRat (119) 1000
  V := mkRat (1499729) 1000000
  m := mkRat (11977193) 1000000
  M3 := mkRat (9436909) 1000000
  b := mkRat (1) 100
  T := mkRat (-3773519) 250
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (564399) 100000
  bi := mkRat (-643091) 1000000
  tr := mkRat (265399) 100000
  ti := mkRat (-405091) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (65399) 200000
  ply := mkRat (-101273) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (693) 4000
  na := mkRat (-43357) 500000
  nb := mkRat (-996233) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 67`. -/
def d67 : SmData where
  ur := mkRat (83030003700319) 20000000000000
  ui := mkRat (-50863089077829) 100000000000000
  vr := mkRat (-187) 125
  vi := mkRat (29) 250
  V := mkRat (1500491) 1000000
  m := mkRat (12341949) 1000000
  M3 := mkRat (9714671) 1000000
  b := mkRat (1) 100
  T := mkRat (-7779059) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2259) 400
  bi := mkRat (-624631) 1000000
  tr := mkRat (5311) 2000
  ti := mkRat (-392631) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (1311) 4000
  ply := mkRat (-49079) 250000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (1679) 10000
  na := mkRat (-42019) 500000
  nb := mkRat (-498231) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 69`. -/
def d69 : SmData where
  ur := mkRat (12980619713429) 3125000000000
  ui := mkRat (-49405208216171) 100000000000000
  vr := mkRat (-187) 125
  vi := mkRat (14) 125
  V := mkRat (1500187) 1000000
  m := mkRat (2541361) 200000
  M3 := mkRat (9985389) 1000000
  b := mkRat (1) 100
  T := mkRat (-16022163) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2824899) 500000
  bi := mkRat (-151513) 250000
  tr := mkRat (1328899) 500000
  ti := mkRat (-95513) 250000
  rs := mkRat (1) 500000
  plx := mkRat (328899) 1000000
  ply := mkRat (-95513) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (16333) 100000
  na := mkRat (-81749) 1000000
  nb := mkRat (-249163) 250000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 71`. -/
def d71 : SmData where
  ur := mkRat (207795392508409) 50000000000000
  ui := mkRat (-24014082461289) 50000000000000
  vr := mkRat (-187) 125
  vi := mkRat (109) 1000
  V := mkRat (749983) 500000
  m := mkRat (13071753) 1000000
  M3 := mkRat (10257109) 1000000
  b := mkRat (1) 100
  T := mkRat (-1648621) 100
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1412977) 250000
  bi := mkRat (-294641) 500000
  tr := mkRat (664977) 250000
  ti := mkRat (-185641) 500000
  rs := mkRat (1) 500000
  plx := mkRat (164977) 500000
  ply := mkRat (-185641) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (3967) 25000
  na := mkRat (-1241) 15625
  nb := mkRat (-24921) 25000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 73`. -/
def d73 : SmData where
  ur := mkRat (415784894261533) 100000000000000
  ui := mkRat (-46725448920647) 100000000000000
  vr := mkRat (-187) 125
  vi := mkRat (53) 500
  V := mkRat (1499751) 1000000
  m := mkRat (2687357) 200000
  M3 := mkRat (2632309) 250000
  b := mkRat (1) 100
  T := mkRat (-847513) 50
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5653849) 1000000
  bi := mkRat (-286627) 500000
  tr := mkRat (2661849) 1000000
  ti := mkRat (-180627) 500000
  rs := mkRat (1) 500000
  plx := mkRat (13237) 40000
  ply := mkRat (-180627) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (3859) 25000
  na := mkRat (-77259) 1000000
  nb := mkRat (-99701) 100000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 75`. -/
def d75 : SmData where
  ur := mkRat (10399097751699) 2500000000000
  ui := mkRat (-22745613742233) 50000000000000
  vr := mkRat (-187) 125
  vi := mkRat (13) 125
  V := mkRat (1499611) 1000000
  m := mkRat (6900947) 500000
  M3 := mkRat (10802287) 1000000
  b := mkRat (1) 100
  T := mkRat (-2176789) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5655639) 1000000
  bi := mkRat (-8733) 15625
  tr := mkRat (2663639) 1000000
  ti := mkRat (-5483) 15625
  rs := mkRat (1) 500000
  plx := mkRat (331819) 1000000
  ply := mkRat (-5483) 31250
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (14991) 100000
  na := mkRat (-9379) 125000
  nb := mkRat (-997181) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 77`. -/
def d77 : SmData where
  ur := mkRat (416129362008153) 100000000000000
  ui := mkRat (-2770016245973) 6250000000000
  vr := mkRat (-1497) 1000
  vi := mkRat (101) 1000
  V := mkRat (375101) 250000
  m := mkRat (566683) 40000
  M3 := mkRat (1385411) 125000
  b := mkRat (1) 100
  T := mkRat (-8939183) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2829147) 500000
  bi := mkRat (-544203) 1000000
  tr := mkRat (1332147) 500000
  ti := mkRat (-342203) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (332147) 1000000
  ply := mkRat (-85551) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (14619) 100000
  na := mkRat (-7317) 100000
  nb := mkRat (-997319) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 79`. -/
def d79 : SmData where
  ur := mkRat (52035323827033) 12500000000000
  ui := mkRat (-21603912354737) 50000000000000
  vr := mkRat (-1497) 1000
  vi := mkRat (49) 500
  V := mkRat (300041) 200000
  m := mkRat (7266161) 500000
  M3 := mkRat (11356639) 1000000
  b := mkRat (1) 100
  T := mkRat (-18342421) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2829913) 500000
  bi := mkRat (-265039) 500000
  tr := mkRat (1332913) 500000
  ti := mkRat (-167039) 500000
  rs := mkRat (1) 500000
  plx := mkRat (332913) 1000000
  ply := mkRat (-167039) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (14269) 100000
  na := mkRat (-35709) 500000
  nb := mkRat (-498723) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 81`. -/
def d81 : SmData where
  ur := mkRat (416424774736197) 100000000000000
  ui := mkRat (-42149656897629) 100000000000000
  vr := mkRat (-1497) 1000
  vi := mkRat (12) 125
  V := mkRat (60003) 40000
  m := mkRat (14897631) 1000000
  M3 := mkRat (11630823) 1000000
  b := mkRat (1) 100
  T := mkRat (-18806479) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (88457) 15625
  bi := mkRat (-517497) 1000000
  tr := mkRat (166703) 62500
  ti := mkRat (-325497) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (41703) 125000
  ply := mkRat (-40687) 250000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (139) 1000
  na := mkRat (-69571) 1000000
  nb := mkRat (-124697) 125000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 83`. -/
def d83 : SmData where
  ur := mkRat (416556954365513) 100000000000000
  ui := mkRat (-20570947279053) 50000000000000
  vr := mkRat (-1497) 1000
  vi := mkRat (47) 500
  V := mkRat (1499949) 1000000
  m := mkRat (3815749) 250000
  M3 := mkRat (5952643) 500000
  b := mkRat (1) 100
  T := mkRat (-9635269) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (566257) 100000
  bi := mkRat (-505419) 1000000
  tr := mkRat (266857) 100000
  ti := mkRat (-317419) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (66857) 200000
  ply := mkRat (-15871) 100000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (13553) 100000
  na := mkRat (-33917) 500000
  nb := mkRat (-15589) 15625
  K := mkRat (80001) 1000

/-- The certificate data for `r = 85`. -/
def d85 : SmData where
  ur := mkRat (52085006227881) 12500000000000
  ui := mkRat (-10045258099397) 25000000000000
  vr := mkRat (-1497) 1000
  vi := mkRat (91) 1000
  V := mkRat (374941) 250000
  m := mkRat (3125683) 200000
  M3 := mkRat (12179443) 1000000
  b := mkRat (1) 100
  T := mkRat (-19734599) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (28319) 5000
  bi := mkRat (-49281) 100000
  tr := mkRat (13349) 5000
  ti := mkRat (-31081) 100000
  rs := mkRat (1) 500000
  plx := mkRat (3349) 10000
  ply := mkRat (-31081) 200000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (3317) 25000
  na := mkRat (-6641) 100000
  nb := mkRat (-31181) 31250
  K := mkRat (80001) 1000

/-- The certificate data for `r = 87`. -/
def d87 : SmData where
  ur := mkRat (416794877900669) 100000000000000
  ui := mkRat (-4907985209367) 12500000000000
  vr := mkRat (-1497) 1000
  vi := mkRat (89) 1000
  V := mkRat (374911) 250000
  m := mkRat (15993883) 1000000
  M3 := mkRat (1556797) 125000
  b := mkRat (1) 100
  T := mkRat (-20198661) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5664949) 1000000
  bi := mkRat (-481639) 1000000
  tr := mkRat (2670949) 1000000
  ti := mkRat (-303639) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (167737) 500000
  ply := mkRat (-7591) 50000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (81) 625
  na := mkRat (-64869) 1000000
  nb := mkRat (-997893) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 89`. -/
def d89 : SmData where
  ur := mkRat (10422554138229) 2500000000000
  ui := mkRat (-7677507075261) 20000000000000
  vr := mkRat (-1497) 1000
  vi := mkRat (87) 1000
  V := mkRat (749763) 500000
  m := mkRat (4089849) 250000
  M3 := mkRat (3182379) 250000
  b := mkRat (1) 100
  T := mkRat (-5165681) 250
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2833011) 500000
  bi := mkRat (-3767) 8000
  tr := mkRat (1336011) 500000
  ti := mkRat (-19) 64
  rs := mkRat (1) 500000
  plx := mkRat (336011) 1000000
  ply := mkRat (-74219) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (1267) 10000
  na := mkRat (-12683) 200000
  nb := mkRat (-997987) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 91`. -/
def d91 : SmData where
  ur := mkRat (208501280692897) 50000000000000
  ui := mkRat (-36669275267) 97656250000
  vr := mkRat (-749) 500
  vi := mkRat (17) 200
  V := mkRat (150041) 100000
  m := mkRat (16724953) 1000000
  M3 := mkRat (813401) 62500
  b := mkRat (1) 100
  T := mkRat (-5281697) 250
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2834013) 500000
  bi := mkRat (-460493) 1000000
  tr := mkRat (1336013) 500000
  ti := mkRat (-290493) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (336013) 1000000
  ply := mkRat (-72623) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (6199) 50000
  na := mkRat (-62057) 1000000
  nb := mkRat (-124759) 125000
  K := mkRat (80001) 1000

/-- The data of chunk 3. -/
def chunk3 : List (ℕ × SmData) :=
  [(63, d63), (65, d65), (67, d67), (69, d69), (71, d71), (73, d73), (75, d75), (77, d77), (79, d79), (81, d81), (83, d83), (85, d85), (87, d87), (89, d89), (91, d91)]

theorem chunk3_ok : chunk3.all (fun p => famCertOK p.1 p.2) = true := by
  decide +kernel

end OddZeta.Small
