import OddZeta.Family.SmallMach

/-!
# Per-`r` certificate data and kernel checks, chunk 1: `r ∈ {3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31}`

Generated by `scripts/small_cert_gen.py`.
-/

set_option linter.style.longLine false

namespace OddZeta.Small

/-- The certificate data for `r = 3`. -/
def d3 : SmData where
  ur := mkRat (-181356272704721) 100000000000000
  ui := mkRat (-228065370049673) 100000000000000
  vr := mkRat (-139) 250
  vi := mkRat (1393) 1000
  V := mkRat (749931) 500000
  m := mkRat (287983) 250000
  M3 := mkRat (387911) 250000
  b := mkRat (1) 100
  T := mkRat (-721787) 1000
  m0 := (-3 : ℤ)
  yR := mkRat (-36737) 10000
  br := mkRat (-1257563) 1000000
  bi := mkRat (-1836827) 500000
  tr := mkRat (-2369563) 1000000
  ti := mkRat (-443827) 500000
  rs := mkRat (1) 500000
  plx := mkRat (-2184781) 1000000
  ply := mkRat (-443827) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4, mkRat (7) 8]
  gT := []
  gL := []
  c0 := mkRat (22169) 50000
  na := mkRat (-184637) 200000
  nb := mkRat (192177) 500000
  K := mkRat (2723) 500

/-- The certificate data for `r = 5`. -/
def d5 : SmData where
  ur := mkRat (7376790042711) 20000000000000
  ui := mkRat (-335100188110929) 100000000000000
  vr := mkRat (-126) 125
  vi := mkRat (1111) 1000
  V := mkRat (1500129) 1000000
  m := mkRat (58133) 40000
  M3 := mkRat (147529) 100000
  b := mkRat (1) 100
  T := mkRat (-236903) 200
  m0 := (-6 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (34421) 25000
  bi := mkRat (-2231001) 500000
  tr := mkRat (-15979) 25000
  ti := mkRat (-1120001) 500000
  rs := mkRat (1) 500000
  plx := mkRat (-65979) 50000
  ply := mkRat (-1120001) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4, mkRat (7) 8]
  gT := []
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-170929) 200000
  nb := mkRat (-519211) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 7`. -/
def d7 : SmData where
  ur := mkRat (84762767213661) 50000000000000
  ui := mkRat (-80873756303379) 25000000000000
  vr := mkRat (-1199) 1000
  vi := mkRat (451) 500
  V := mkRat (750201) 500000
  m := mkRat (1729909) 1000000
  M3 := mkRat (1554213) 1000000
  b := mkRat (1) 100
  T := mkRat (-82309) 50
  m0 := (-7 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (578851) 200000
  bi := mkRat (-82739) 20000
  tr := mkRat (99251) 200000
  ti := mkRat (-46659) 20000
  rs := mkRat (1) 500000
  plx := mkRat (-11748) 15625
  ply := mkRat (-46659) 40000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4, mkRat (7) 8]
  gT := []
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-170701) 250000
  nb := mkRat (-3653) 5000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 9`. -/
def d9 : SmData where
  ur := mkRat (24739955020917) 10000000000000
  ui := mkRat (-290860210216189) 100000000000000
  vr := mkRat (-649) 500
  vi := mkRat (751) 1000
  V := mkRat (749801) 500000
  m := mkRat (405053) 200000
  M3 := mkRat (858951) 500000
  b := mkRat (1) 100
  T := mkRat (-52707) 25
  m0 := (-8 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (942999) 250000
  bi := mkRat (-1829801) 500000
  tr := mkRat (293999) 250000
  ti := mkRat (-1078801) 500000
  rs := mkRat (1) 500000
  plx := mkRat (-206001) 500000
  ply := mkRat (-1078801) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4, mkRat (7) 8]
  gT := []
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-28097) 50000
  nb := mkRat (-827177) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 11`. -/
def d11 : SmData where
  ur := mkRat (295233837535369) 100000000000000
  ui := mkRat (-129022323239389) 50000000000000
  vr := mkRat (-1357) 1000
  vi := mkRat (16) 25
  V := mkRat (30007) 20000
  m := mkRat (2337819) 1000000
  M3 := mkRat (1922207) 1000000
  b := mkRat (1) 100
  T := mkRat (-321356) 125
  m0 := (-8 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2154669) 500000
  bi := mkRat (-1610223) 500000
  tr := mkRat (797669) 500000
  ti := mkRat (-970223) 500000
  rs := mkRat (1) 500000
  plx := mkRat (-202331) 1000000
  ply := mkRat (-970223) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4, mkRat (7) 8]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-59369) 125000
  nb := mkRat (-880011) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 13`. -/
def d13 : SmData where
  ur := mkRat (326144018357043) 100000000000000
  ui := mkRat (-229449805556367) 100000000000000
  vr := mkRat (-1393) 1000
  vi := mkRat (139) 250
  V := mkRat (749931) 500000
  m := mkRat (2662979) 1000000
  M3 := mkRat (1120167) 500000
  b := mkRat (1) 100
  T := mkRat (-3033769) 1000
  m0 := (-8 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (116361) 25000
  bi := mkRat (-1425249) 500000
  tr := mkRat (46711) 25000
  ti := mkRat (-869249) 500000
  rs := mkRat (1) 500000
  plx := mkRat (-3289) 50000
  ply := mkRat (-869249) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4, mkRat (7) 8]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-409913) 1000000
  nb := mkRat (-228031) 250000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 15`. -/
def d15 : SmData where
  ur := mkRat (34705225301909) 10000000000000
  ui := mkRat (-205421019543267) 100000000000000
  vr := mkRat (-709) 500
  vi := mkRat (49) 100
  V := mkRat (60011) 40000
  m := mkRat (93661) 31250
  M3 := mkRat (2457707) 1000000
  b := mkRat (1) 100
  T := mkRat (-699389) 200
  m0 := (-8 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (4888523) 1000000
  bi := mkRat (-254421) 100000
  tr := mkRat (2052523) 1000000
  ti := mkRat (-156421) 100000
  rs := mkRat (1) 500000
  plx := mkRat (26261) 1000000
  ply := mkRat (-156421) 200000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4, mkRat (7) 8]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-360091) 1000000
  nb := mkRat (-932917) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 17`. -/
def d17 : SmData where
  ur := mkRat (36176061003399) 10000000000000
  ui := mkRat (-92676757914423) 50000000000000
  vr := mkRat (-287) 200
  vi := mkRat (437) 1000
  V := mkRat (300013) 200000
  m := mkRat (3337841) 1000000
  M3 := mkRat (2659291) 1000000
  b := mkRat (1) 100
  T := mkRat (-1980153) 500
  m0 := (-8 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2526303) 500000
  bi := mkRat (-458107) 200000
  tr := mkRat (1091303) 500000
  ti := mkRat (-283307) 200000
  rs := mkRat (1) 500000
  plx := mkRat (91303) 1000000
  ply := mkRat (-177067) 250000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4, mkRat (7) 8]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-12831) 40000
  nb := mkRat (-189431) 200000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 19`. -/
def d19 : SmData where
  ur := mkRat (14898283005179) 4000000000000
  ui := mkRat (-16852262400049) 10000000000000
  vr := mkRat (-1447) 1000
  vi := mkRat (79) 200
  V := mkRat (299989) 200000
  m := mkRat (736667) 200000
  M3 := mkRat (2894441) 1000000
  b := mkRat (1) 100
  T := mkRat (-1105951) 250
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5171571) 1000000
  bi := mkRat (-1040113) 500000
  tr := mkRat (2277571) 1000000
  ti := mkRat (-645113) 500000
  rs := mkRat (1) 500000
  plx := mkRat (69393) 500000
  ply := mkRat (-645113) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4, mkRat (7) 8]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-11551) 40000
  nb := mkRat (-239349) 250000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 21`. -/
def d21 : SmData where
  ur := mkRat (380458113592813) 100000000000000
  ui := mkRat (-154293221501763) 100000000000000
  vr := mkRat (-182) 125
  vi := mkRat (359) 1000
  V := mkRat (749803) 500000
  m := mkRat (80649) 20000
  M3 := mkRat (3151339) 1000000
  b := mkRat (1) 100
  T := mkRat (-1221851) 250
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5260581) 1000000
  bi := mkRat (-475483) 250000
  tr := mkRat (2348581) 1000000
  ti := mkRat (-295983) 250000
  rs := mkRat (1) 500000
  plx := mkRat (17429) 100000
  ply := mkRat (-295983) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4, mkRat (7) 8]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-52539) 200000
  nb := mkRat (-482439) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 23`. -/
def d23 : SmData where
  ur := mkRat (15463532189523) 4000000000000
  ui := mkRat (-142153640648529) 100000000000000
  vr := mkRat (-1463) 1000
  vi := mkRat (33) 100
  V := mkRat (1499757) 1000000
  m := mkRat (4384347) 1000000
  M3 := mkRat (1712679) 500000
  b := mkRat (1) 100
  T := mkRat (-5351083) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5328883) 1000000
  bi := mkRat (-109471) 62500
  tr := mkRat (2402883) 1000000
  ti := mkRat (-68221) 62500
  rs := mkRat (1) 500000
  plx := mkRat (100721) 500000
  ply := mkRat (-68221) 125000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4, mkRat (7) 8]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-240629) 1000000
  nb := mkRat (-970617) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 25`. -/
def d25 : SmData where
  ur := mkRat (391382841711211) 100000000000000
  ui := mkRat (-131702653359539) 100000000000000
  vr := mkRat (-1469) 1000
  vi := mkRat (61) 200
  V := mkRat (1500329) 1000000
  m := mkRat (4738423) 1000000
  M3 := mkRat (3712663) 1000000
  b := mkRat (1) 100
  T := mkRat (-726853) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1345707) 250000
  bi := mkRat (-1622027) 1000000
  tr := mkRat (611207) 250000
  ti := mkRat (-1012027) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (111207) 500000
  ply := mkRat (-253007) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4, mkRat (7) 8]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-55501) 250000
  nb := mkRat (-195009) 200000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 27`. -/
def d27 : SmData where
  ur := mkRat (79040028879227) 20000000000000
  ui := mkRat (-122627533468641) 100000000000000
  vr := mkRat (-1473) 1000
  vi := mkRat (283) 1000
  V := mkRat (74997) 50000
  m := mkRat (5094233) 1000000
  M3 := mkRat (1001689) 250000
  b := mkRat (1) 100
  T := mkRat (-6278613) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-15093) 10000
  br := mkRat (5425001) 1000000
  bi := mkRat (-60371) 40000
  tr := mkRat (2479001) 1000000
  ti := mkRat (-37731) 40000
  rs := mkRat (1) 500000
  plx := mkRat (479) 2000
  ply := mkRat (-235819) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (20587) 50000
  na := mkRat (-206079) 1000000
  nb := mkRat (-195707) 200000
  K := mkRat (13253) 1000

/-- The certificate data for `r = 29`. -/
def d29 : SmData where
  ur := mkRat (49785869794529) 12500000000000
  ui := mkRat (-11468384561219) 10000000000000
  vr := mkRat (-1477) 1000
  vi := mkRat (33) 125
  V := mkRat (1500409) 1000000
  m := mkRat (2725721) 500000
  M3 := mkRat (4311021) 1000000
  b := mkRat (1) 100
  T := mkRat (-3371221) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-14109) 10000
  br := mkRat (545987) 100000
  bi := mkRat (-705419) 500000
  tr := mkRat (250587) 100000
  ti := mkRat (-441419) 500000
  rs := mkRat (1) 500000
  plx := mkRat (50587) 200000
  ply := mkRat (-441419) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (2401) 6250
  na := mkRat (-96137) 500000
  nb := mkRat (-981341) 1000000
  K := mkRat (14177) 1000

/-- The certificate data for `r = 31`. -/
def d31 : SmData where
  ur := mkRat (200408667955353) 50000000000000
  ui := mkRat (-107679233057221) 100000000000000
  vr := mkRat (-1479) 1000
  vi := mkRat (247) 1000
  V := mkRat (374871) 250000
  m := mkRat (2904899) 500000
  M3 := mkRat (2308443) 500000
  b := mkRat (1) 100
  T := mkRat (-900788) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5487173) 1000000
  bi := mkRat (-82737) 62500
  tr := mkRat (2529173) 1000000
  ti := mkRat (-25931) 31250
  rs := mkRat (1) 500000
  plx := mkRat (264587) 1000000
  ply := mkRat (-25931) 62500
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-18021) 100000
  nb := mkRat (-983627) 1000000
  K := mkRat (80001) 1000

theorem ok3 : famCertOK 3 d3 = true := by
  decide +kernel

theorem ok5 : famCertOK 5 d5 = true := by
  decide +kernel

theorem ok7 : famCertOK 7 d7 = true := by
  decide +kernel

theorem ok9 : famCertOK 9 d9 = true := by
  decide +kernel

theorem ok11 : famCertOK 11 d11 = true := by
  decide +kernel

theorem ok13 : famCertOK 13 d13 = true := by
  decide +kernel

theorem ok15 : famCertOK 15 d15 = true := by
  decide +kernel

theorem ok17 : famCertOK 17 d17 = true := by
  decide +kernel

theorem ok19 : famCertOK 19 d19 = true := by
  decide +kernel

theorem ok21 : famCertOK 21 d21 = true := by
  decide +kernel

theorem ok23 : famCertOK 23 d23 = true := by
  decide +kernel

theorem ok25 : famCertOK 25 d25 = true := by
  decide +kernel

theorem ok27 : famCertOK 27 d27 = true := by
  decide +kernel

theorem ok29 : famCertOK 29 d29 = true := by
  decide +kernel

theorem ok31 : famCertOK 31 d31 = true := by
  decide +kernel

/-- The data of chunk 1. -/
def chunk1 : List (ℕ × SmData) :=
  [(3, d3), (5, d5), (7, d7), (9, d9), (11, d11), (13, d13), (15, d15), (17, d17), (19, d19), (21, d21), (23, d23), (25, d25), (27, d27), (29, d29), (31, d31)]

theorem chunk1_ok : ∀ p ∈ chunk1, famCertOK p.1 p.2 = true :=
  List.forall_mem_cons.2 ⟨ok3,
    List.forall_mem_cons.2 ⟨ok5,
    List.forall_mem_cons.2 ⟨ok7,
    List.forall_mem_cons.2 ⟨ok9,
    List.forall_mem_cons.2 ⟨ok11,
    List.forall_mem_cons.2 ⟨ok13,
    List.forall_mem_cons.2 ⟨ok15,
    List.forall_mem_cons.2 ⟨ok17,
    List.forall_mem_cons.2 ⟨ok19,
    List.forall_mem_cons.2 ⟨ok21,
    List.forall_mem_cons.2 ⟨ok23,
    List.forall_mem_cons.2 ⟨ok25,
    List.forall_mem_cons.2 ⟨ok27,
    List.forall_mem_cons.2 ⟨ok29,
    List.forall_mem_cons.2 ⟨ok31,
    List.forall_mem_nil _⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩

end OddZeta.Small
