import OddZeta.Family.SmallMach

/-!
# Per-`r` certificate data and kernel checks, chunk 10: `r ∈ {273, 275, 277, 279, 281, 283, 285, 287, 289, 291, 293, 295, 297, 299}`

Generated by `scripts/small_cert_gen.py`.
-/

set_option linter.style.longLine false

namespace OddZeta.Small

/-- The certificate data for `r = 273`. -/
def d273 : SmData where
  ur := mkRat (419006159573677) 100000000000000
  ui := mkRat (-12553567934431) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (29) 1000
  V := mkRat (1500281) 1000000
  m := mkRat (10009647) 200000
  M3 := mkRat (19234947) 500000
  b := mkRat (1) 100
  T := mkRat (-1583957) 25
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2845031) 500000
  bi := mkRat (-19317) 125000
  tr := mkRat (1345031) 500000
  ti := mkRat (-12067) 125000
  rs := mkRat (1) 500000
  plx := mkRat (345031) 1000000
  ply := mkRat (-12067) 250000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4111) 100000
  na := mkRat (-10289) 500000
  nb := mkRat (-249947) 250000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 275`. -/
def d275 : SmData where
  ur := mkRat (209504991807237) 50000000000000
  ui := mkRat (-12462342884277) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (7) 250
  V := mkRat (750131) 500000
  m := mkRat (50414631) 1000000
  M3 := mkRat (38750103) 1000000
  b := mkRat (1) 100
  T := mkRat (-7977796) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (56901) 10000
  bi := mkRat (-152623) 1000000
  tr := mkRat (26901) 10000
  ti := mkRat (-96623) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (6901) 20000
  ply := mkRat (-6039) 125000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (823) 20000
  na := mkRat (-20597) 1000000
  nb := mkRat (-999787) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 277`. -/
def d277 : SmData where
  ur := mkRat (419013727784277) 100000000000000
  ui := mkRat (-6186216840377) 50000000000000
  vr := mkRat (-3) 2
  vi := mkRat (7) 250
  V := mkRat (750131) 500000
  m := mkRat (50781027) 1000000
  M3 := mkRat (39030853) 1000000
  b := mkRat (1) 100
  T := mkRat (-8035807) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5690137) 1000000
  bi := mkRat (-37931) 250000
  tr := mkRat (2690137) 1000000
  ti := mkRat (-23931) 250000
  rs := mkRat (1) 500000
  plx := mkRat (86267) 250000
  ply := mkRat (-23931) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (1019) 25000
  na := mkRat (-4081) 200000
  nb := mkRat (-999791) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 279`. -/
def d279 : SmData where
  ur := mkRat (419017394326293) 100000000000000
  ui := mkRat (-12283812066779) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (7) 250
  V := mkRat (750131) 500000
  m := mkRat (25573713) 500000
  M3 := mkRat (3931161) 100000
  b := mkRat (1) 100
  T := mkRat (-8093818) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2845087) 500000
  bi := mkRat (-75419) 500000
  tr := mkRat (1345087) 500000
  ti := mkRat (-47419) 500000
  rs := mkRat (1) 500000
  plx := mkRat (345087) 1000000
  ply := mkRat (-47419) 1000000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4039) 100000
  na := mkRat (-2527) 125000
  nb := mkRat (-199959) 200000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 281`. -/
def d281 : SmData where
  ur := mkRat (209510492702517) 50000000000000
  ui := mkRat (-12196450588339) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (7) 250
  V := mkRat (750131) 500000
  m := mkRat (25756913) 500000
  M3 := mkRat (39592373) 1000000
  b := mkRat (1) 100
  T := mkRat (-8151829) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (569021) 100000
  bi := mkRat (-29993) 200000
  tr := mkRat (269021) 100000
  ti := mkRat (-18793) 200000
  rs := mkRat (1) 500000
  plx := mkRat (69021) 200000
  ply := mkRat (-23491) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4001) 100000
  na := mkRat (-2003) 100000
  nb := mkRat (-999799) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 283`. -/
def d283 : SmData where
  ur := mkRat (419024503109619) 100000000000000
  ui := mkRat (-1513790320771) 12500000000000
  vr := mkRat (-3) 2
  vi := mkRat (7) 250
  V := mkRat (750131) 500000
  m := mkRat (51880227) 1000000
  M3 := mkRat (39873143) 1000000
  b := mkRat (1) 100
  T := mkRat (-65678721) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1138049) 200000
  bi := mkRat (-149103) 1000000
  tr := mkRat (538049) 200000
  ti := mkRat (-93103) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (172561) 500000
  ply := mkRat (-5819) 125000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (793) 20000
  na := mkRat (-9923) 500000
  nb := mkRat (-999803) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 285`. -/
def d285 : SmData where
  ur := mkRat (26189246841057) 6250000000000
  ui := mkRat (-751587629289) 6250000000000
  vr := mkRat (-3) 2
  vi := mkRat (27) 1000
  V := mkRat (1500243) 1000000
  m := mkRat (52246629) 1000000
  M3 := mkRat (40153363) 1000000
  b := mkRat (1) 100
  T := mkRat (-66142809) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5690279) 1000000
  bi := mkRat (-73627) 500000
  tr := mkRat (2690279) 1000000
  ti := mkRat (-46627) 500000
  rs := mkRat (1) 500000
  plx := mkRat (345139) 1000000
  ply := mkRat (-46627) 1000000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (3971) 100000
  na := mkRat (-9939) 500000
  nb := mkRat (-499901) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 287`. -/
def d287 : SmData where
  ur := mkRat (26189457899657) 6250000000000
  ui := mkRat (-2985415971421) 25000000000000
  vr := mkRat (-3) 2
  vi := mkRat (27) 1000
  V := mkRat (1500243) 1000000
  m := mkRat (52613033) 1000000
  M3 := mkRat (20217071) 500000
  b := mkRat (1) 100
  T := mkRat (-66606897) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5690313) 1000000
  bi := mkRat (-146417) 1000000
  tr := mkRat (2690313) 1000000
  ti := mkRat (-92417) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (345157) 1000000
  ply := mkRat (-722) 15625
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (787) 20000
  na := mkRat (-19699) 1000000
  nb := mkRat (-199961) 200000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 289`. -/
def d289 : SmData where
  ur := mkRat (83806927160719) 20000000000000
  ui := mkRat (-1185908350403) 10000000000000
  vr := mkRat (-3) 2
  vi := mkRat (27) 1000
  V := mkRat (1500243) 1000000
  m := mkRat (26489719) 500000
  M3 := mkRat (40714927) 1000000
  b := mkRat (1) 100
  T := mkRat (-33535493) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2845173) 500000
  bi := mkRat (-145591) 1000000
  tr := mkRat (1345173) 500000
  ti := mkRat (-91591) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (345173) 1000000
  ply := mkRat (-11449) 250000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (39) 1000
  na := mkRat (-4881) 250000
  nb := mkRat (-999809) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 291`. -/
def d291 : SmData where
  ur := mkRat (419037879501623) 100000000000000
  ui := mkRat (-2944409270787) 25000000000000
  vr := mkRat (-3) 2
  vi := mkRat (27) 1000
  V := mkRat (1500243) 1000000
  m := mkRat (13336461) 250000
  M3 := mkRat (40995719) 1000000
  b := mkRat (1) 100
  T := mkRat (-33767537) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5690379) 1000000
  bi := mkRat (-18097) 125000
  tr := mkRat (2690379) 1000000
  ti := mkRat (-11347) 125000
  rs := mkRat (1) 500000
  plx := mkRat (34519) 100000
  ply := mkRat (-11347) 250000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (1933) 50000
  na := mkRat (-387) 20000
  nb := mkRat (-249953) 250000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 293`. -/
def d293 : SmData where
  ur := mkRat (209520529622463) 50000000000000
  ui := mkRat (-2339460286483) 20000000000000
  vr := mkRat (-3) 2
  vi := mkRat (27) 1000
  V := mkRat (1500243) 1000000
  m := mkRat (13428063) 250000
  M3 := mkRat (10319129) 250000
  b := mkRat (1) 100
  T := mkRat (-33999581) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5690411) 1000000
  bi := mkRat (-143973) 1000000
  tr := mkRat (2690411) 1000000
  ti := mkRat (-89973) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (172603) 500000
  ply := mkRat (-22493) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (3831) 100000
  na := mkRat (-9589) 500000
  nb := mkRat (-124977) 125000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 295`. -/
def d295 : SmData where
  ur := mkRat (419044176731159) 100000000000000
  ui := mkRat (-2323610797821) 20000000000000
  vr := mkRat (-3) 2
  vi := mkRat (13) 500
  V := mkRat (750113) 500000
  m := mkRat (54078661) 1000000
  M3 := mkRat (41556803) 1000000
  b := mkRat (1) 100
  T := mkRat (-68463251) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2845221) 500000
  bi := mkRat (-142181) 1000000
  tr := mkRat (1345221) 500000
  ti := mkRat (-90181) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (345221) 1000000
  ply := mkRat (-4509) 100000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (24) 625
  na := mkRat (-9611) 500000
  nb := mkRat (-199963) 200000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 297`. -/
def d297 : SmData where
  ur := mkRat (419047233601647) 100000000000000
  ui := mkRat (-1153987279729) 10000000000000
  vr := mkRat (-3) 2
  vi := mkRat (13) 500
  V := mkRat (750113) 500000
  m := mkRat (54445071) 1000000
  M3 := mkRat (41837609) 1000000
  b := mkRat (1) 100
  T := mkRat (-68927339) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (711309) 125000
  bi := mkRat (-141399) 1000000
  tr := mkRat (336309) 125000
  ti := mkRat (-89399) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (86309) 250000
  ply := mkRat (-447) 10000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (3807) 100000
  na := mkRat (-1191) 62500
  nb := mkRat (-499909) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 299`. -/
def d299 : SmData where
  ur := mkRat (419050231443621) 100000000000000
  ui := mkRat (-11462736487583) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (13) 500
  V := mkRat (750113) 500000
  m := mkRat (27405741) 500000
  M3 := mkRat (2105921) 50000
  b := mkRat (1) 100
  T := mkRat (-17347857) 250
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2845251) 500000
  bi := mkRat (-140627) 1000000
  tr := mkRat (1345251) 500000
  ti := mkRat (-88627) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (345251) 1000000
  ply := mkRat (-22157) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (1887) 50000
  na := mkRat (-18891) 1000000
  nb := mkRat (-999821) 1000000
  K := mkRat (80001) 1000

/-- The data of chunk 10. -/
def chunk10 : List (ℕ × SmData) :=
  [(273, d273), (275, d275), (277, d277), (279, d279), (281, d281), (283, d283), (285, d285), (287, d287), (289, d289), (291, d291), (293, d293), (295, d295), (297, d297), (299, d299)]

theorem chunk10_ok : chunk10.all (fun p => famCertOK p.1 p.2) = true := by
  decide +kernel

end OddZeta.Small
