import OddZeta.Family.SmallMach

/-!
# Per-`r` certificate data and kernel checks, chunk 9: `r ∈ {243, 245, 247, 249, 251, 253, 255, 257, 259, 261, 263, 265, 267, 269, 271}`

Generated by `scripts/small_cert_gen.py`.
-/

set_option linter.style.longLine false

namespace OddZeta.Small

/-- The certificate data for `r = 243`. -/
def d243 : SmData where
  ur := mkRat (418937402418561) 100000000000000
  ui := mkRat (-7050950416821) 50000000000000
  vr := mkRat (-3) 2
  vi := mkRat (4) 125
  V := mkRat (750171) 500000
  m := mkRat (8910501) 200000
  M3 := mkRat (8565297) 250000
  b := mkRat (1) 100
  T := mkRat (-14099241) 250
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2844687) 500000
  bi := mkRat (-173019) 1000000
  tr := mkRat (1344687) 500000
  ti := mkRat (-109019) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (344687) 1000000
  ply := mkRat (-5451) 100000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4643) 100000
  na := mkRat (-11621) 500000
  nb := mkRat (-999729) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 245`. -/
def d245 : SmData where
  ur := mkRat (209471379804333) 50000000000000
  ui := mkRat (-6993448983947) 50000000000000
  vr := mkRat (-3) 2
  vi := mkRat (4) 125
  V := mkRat (750171) 500000
  m := mkRat (22459437) 500000
  M3 := mkRat (1727091) 50000
  b := mkRat (1) 100
  T := mkRat (-56861051) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1422357) 250000
  bi := mkRat (-171869) 1000000
  tr := mkRat (672357) 250000
  ti := mkRat (-107869) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (172357) 500000
  ply := mkRat (-26967) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (2297) 50000
  na := mkRat (-5749) 250000
  nb := mkRat (-199947) 200000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 247`. -/
def d247 : SmData where
  ur := mkRat (2618424943569) 625000000000
  ui := mkRat (-6936877447637) 50000000000000
  vr := mkRat (-3) 2
  vi := mkRat (4) 125
  V := mkRat (750171) 500000
  m := mkRat (9057049) 200000
  M3 := mkRat (34822461) 1000000
  b := mkRat (1) 100
  T := mkRat (-57325139) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (142237) 25000
  bi := mkRat (-85369) 500000
  tr := mkRat (67237) 25000
  ti := mkRat (-53369) 500000
  rs := mkRat (1) 500000
  plx := mkRat (17237) 50000
  ply := mkRat (-53369) 1000000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (2273) 50000
  na := mkRat (-4551) 200000
  nb := mkRat (-999741) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 249`. -/
def d249 : SmData where
  ur := mkRat (209476550234963) 50000000000000
  ui := mkRat (-6881213440817) 50000000000000
  vr := mkRat (-3) 2
  vi := mkRat (31) 1000
  V := mkRat (1500321) 1000000
  m := mkRat (22825809) 500000
  M3 := mkRat (17551287) 500000
  b := mkRat (1) 100
  T := mkRat (-28894613) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5689531) 1000000
  bi := mkRat (-10539) 62500
  tr := mkRat (2689531) 1000000
  ti := mkRat (-1666) 15625
  rs := mkRat (1) 500000
  plx := mkRat (172383) 500000
  ply := mkRat (-833) 15625
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4541) 100000
  na := mkRat (-2273) 100000
  nb := mkRat (-999741) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 251`. -/
def d251 : SmData where
  ur := mkRat (418958091913801) 100000000000000
  ui := mkRat (-6826435307761) 50000000000000
  vr := mkRat (-3) 2
  vi := mkRat (31) 1000
  V := mkRat (1500321) 1000000
  m := mkRat (46017993) 1000000
  M3 := mkRat (3538323) 100000
  b := mkRat (1) 100
  T := mkRat (-29126657) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5689581) 1000000
  bi := mkRat (-167529) 1000000
  tr := mkRat (2689581) 1000000
  ti := mkRat (-105529) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (34479) 100000
  ply := mkRat (-13191) 250000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (2247) 50000
  na := mkRat (-703) 31250
  nb := mkRat (-499873) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 253`. -/
def d253 : SmData where
  ur := mkRat (418962968962689) 100000000000000
  ui := mkRat (-13545044152087) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (31) 1000
  V := mkRat (1500321) 1000000
  m := mkRat (46384369) 1000000
  M3 := mkRat (7132779) 200000
  b := mkRat (1) 100
  T := mkRat (-58717401) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (568963) 100000
  bi := mkRat (-3329) 20000
  tr := mkRat (268963) 100000
  ti := mkRat (-2089) 20000
  rs := mkRat (1) 500000
  plx := mkRat (68963) 200000
  ply := mkRat (-2089) 40000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (139) 3125
  na := mkRat (-22267) 1000000
  nb := mkRat (-124969) 125000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 255`. -/
def d255 : SmData where
  ur := mkRat (83793547027013) 20000000000000
  ui := mkRat (-1679863357453) 12500000000000
  vr := mkRat (-3) 2
  vi := mkRat (31) 1000
  V := mkRat (1500321) 1000000
  m := mkRat (11687687) 250000
  M3 := mkRat (3594457) 100000
  b := mkRat (1) 100
  T := mkRat (-59181489) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5689677) 1000000
  bi := mkRat (-165389) 1000000
  tr := mkRat (2689677) 1000000
  ti := mkRat (-103389) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (344839) 1000000
  ply := mkRat (-25847) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4403) 100000
  na := mkRat (-551) 25000
  nb := mkRat (-999757) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 257`. -/
def d257 : SmData where
  ur := mkRat (418972393814399) 100000000000000
  ui := mkRat (-416700605269) 3125000000000
  vr := mkRat (-3) 2
  vi := mkRat (3) 100
  V := mkRat (15003) 10000
  m := mkRat (47117129) 1000000
  M3 := mkRat (18112349) 500000
  b := mkRat (1) 100
  T := mkRat (-7455697) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1422431) 250000
  bi := mkRat (-10209) 62500
  tr := mkRat (672431) 250000
  ti := mkRat (-6459) 62500
  rs := mkRat (1) 500000
  plx := mkRat (172431) 500000
  ply := mkRat (-6459) 125000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4401) 100000
  na := mkRat (-2203) 100000
  nb := mkRat (-999757) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 259`. -/
def d259 : SmData where
  ur := mkRat (418976948255333) 100000000000000
  ui := mkRat (-51685716887) 390625000000
  vr := mkRat (-3) 2
  vi := mkRat (3) 100
  V := mkRat (15003) 10000
  m := mkRat (47483511) 1000000
  M3 := mkRat (18252693) 500000
  b := mkRat (1) 100
  T := mkRat (-7513708) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5689769) 1000000
  bi := mkRat (-32463) 200000
  tr := mkRat (2689769) 1000000
  ti := mkRat (-20463) 200000
  rs := mkRat (1) 500000
  plx := mkRat (68977) 200000
  ply := mkRat (-25579) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4357) 100000
  na := mkRat (-21811) 1000000
  nb := mkRat (-499881) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 261`. -/
def d261 : SmData where
  ur := mkRat (418981401589549) 100000000000000
  ui := mkRat (-1313024233423) 10000000000000
  vr := mkRat (-3) 2
  vi := mkRat (3) 100
  V := mkRat (15003) 10000
  m := mkRat (9569979) 200000
  M3 := mkRat (18393041) 500000
  b := mkRat (1) 100
  T := mkRat (-7571719) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2844907) 500000
  bi := mkRat (-80651) 500000
  tr := mkRat (1344907) 500000
  ti := mkRat (-50651) 500000
  rs := mkRat (1) 500000
  plx := mkRat (344907) 1000000
  ply := mkRat (-50651) 1000000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (2157) 50000
  na := mkRat (-4319) 200000
  nb := mkRat (-499883) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 263`. -/
def d263 : SmData where
  ur := mkRat (41898575683131) 10000000000000
  ui := mkRat (-6515239968099) 50000000000000
  vr := mkRat (-3) 2
  vi := mkRat (3) 100
  V := mkRat (15003) 10000
  m := mkRat (48216281) 1000000
  M3 := mkRat (37066787) 1000000
  b := mkRat (1) 100
  T := mkRat (-1525946) 25
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2844929) 500000
  bi := mkRat (-32061) 200000
  tr := mkRat (1344929) 500000
  ti := mkRat (-20061) 200000
  rs := mkRat (1) 500000
  plx := mkRat (344929) 1000000
  ply := mkRat (-6269) 125000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (267) 6250
  na := mkRat (-10691) 500000
  nb := mkRat (-999771) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 265`. -/
def d265 : SmData where
  ur := mkRat (16759600675309) 4000000000000
  ui := mkRat (-12932221543717) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (29) 1000
  V := mkRat (1500281) 1000000
  m := mkRat (48582669) 1000000
  M3 := mkRat (18673491) 500000
  b := mkRat (1) 100
  T := mkRat (-7687741) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (56899) 10000
  bi := mkRat (-79161) 500000
  tr := mkRat (26899) 10000
  ti := mkRat (-50161) 500000
  rs := mkRat (1) 500000
  plx := mkRat (6899) 20000
  ply := mkRat (-50161) 1000000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (267) 6250
  na := mkRat (-10693) 500000
  nb := mkRat (-999771) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 267`. -/
def d267 : SmData where
  ur := mkRat (418994184538729) 100000000000000
  ui := mkRat (-641771670589) 5000000000000
  vr := mkRat (-3) 2
  vi := mkRat (29) 1000
  V := mkRat (1500281) 1000000
  m := mkRat (24474529) 500000
  M3 := mkRat (18813849) 500000
  b := mkRat (1) 100
  T := mkRat (-7745752) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2844971) 500000
  bi := mkRat (-78677) 500000
  tr := mkRat (1344971) 500000
  ti := mkRat (-49677) 500000
  rs := mkRat (1) 500000
  plx := mkRat (344971) 1000000
  ply := mkRat (-49677) 1000000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4231) 100000
  na := mkRat (-21179) 1000000
  nb := mkRat (-39991) 40000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 269`. -/
def d269 : SmData where
  ur := mkRat (83799652498363) 20000000000000
  ui := mkRat (-159251034963) 1250000000000
  vr := mkRat (-3) 2
  vi := mkRat (29) 1000
  V := mkRat (1500281) 1000000
  m := mkRat (49315449) 1000000
  M3 := mkRat (37908423) 1000000
  b := mkRat (1) 100
  T := mkRat (-7803763) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5689983) 1000000
  bi := mkRat (-156401) 1000000
  tr := mkRat (2689983) 1000000
  ti := mkRat (-98401) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (344991) 1000000
  ply := mkRat (-123) 2500
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4191) 100000
  na := mkRat (-1311) 62500
  nb := mkRat (-999779) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 271`. -/
def d271 : SmData where
  ur := mkRat (419002253336519) 100000000000000
  ui := mkRat (-12646137920937) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (29) 1000
  V := mkRat (1500281) 1000000
  m := mkRat (49681841) 1000000
  M3 := mkRat (7637831) 200000
  b := mkRat (1) 100
  T := mkRat (-7861774) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5690023) 1000000
  bi := mkRat (-155461) 1000000
  tr := mkRat (2690023) 1000000
  ti := mkRat (-97461) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (86253) 250000
  ply := mkRat (-4873) 100000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (83) 2000
  na := mkRat (-831) 40000
  nb := mkRat (-124973) 125000
  K := mkRat (80001) 1000

theorem ok243 : famCertOK 243 d243 = true := by
  decide +kernel

theorem ok245 : famCertOK 245 d245 = true := by
  decide +kernel

theorem ok247 : famCertOK 247 d247 = true := by
  decide +kernel

theorem ok249 : famCertOK 249 d249 = true := by
  decide +kernel

theorem ok251 : famCertOK 251 d251 = true := by
  decide +kernel

theorem ok253 : famCertOK 253 d253 = true := by
  decide +kernel

theorem ok255 : famCertOK 255 d255 = true := by
  decide +kernel

theorem ok257 : famCertOK 257 d257 = true := by
  decide +kernel

theorem ok259 : famCertOK 259 d259 = true := by
  decide +kernel

theorem ok261 : famCertOK 261 d261 = true := by
  decide +kernel

theorem ok263 : famCertOK 263 d263 = true := by
  decide +kernel

theorem ok265 : famCertOK 265 d265 = true := by
  decide +kernel

theorem ok267 : famCertOK 267 d267 = true := by
  decide +kernel

theorem ok269 : famCertOK 269 d269 = true := by
  decide +kernel

theorem ok271 : famCertOK 271 d271 = true := by
  decide +kernel

/-- The data of chunk 9. -/
def chunk9 : List (ℕ × SmData) :=
  [(243, d243), (245, d245), (247, d247), (249, d249), (251, d251), (253, d253), (255, d255), (257, d257), (259, d259), (261, d261), (263, d263), (265, d265), (267, d267), (269, d269), (271, d271)]

theorem chunk9_ok : ∀ p ∈ chunk9, famCertOK p.1 p.2 = true :=
  List.forall_mem_cons.2 ⟨ok243,
    List.forall_mem_cons.2 ⟨ok245,
    List.forall_mem_cons.2 ⟨ok247,
    List.forall_mem_cons.2 ⟨ok249,
    List.forall_mem_cons.2 ⟨ok251,
    List.forall_mem_cons.2 ⟨ok253,
    List.forall_mem_cons.2 ⟨ok255,
    List.forall_mem_cons.2 ⟨ok257,
    List.forall_mem_cons.2 ⟨ok259,
    List.forall_mem_cons.2 ⟨ok261,
    List.forall_mem_cons.2 ⟨ok263,
    List.forall_mem_cons.2 ⟨ok265,
    List.forall_mem_cons.2 ⟨ok267,
    List.forall_mem_cons.2 ⟨ok269,
    List.forall_mem_cons.2 ⟨ok271,
    List.forall_mem_nil _⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩

end OddZeta.Small
