import OddZeta.Family.SmallMach

/-!
# Per-`r` certificate data and kernel checks, chunk 5: `r ∈ {123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151}`

Generated by `scripts/small_cert_gen.py`.
-/

set_option linter.style.longLine false

namespace OddZeta.Small

/-- The certificate data for `r = 123`. -/
def d123 : SmData where
  ur := mkRat (8360189203297) 2000000000000
  ui := mkRat (-13910664350669) 50000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (63) 1000
  V := mkRat (375081) 250000
  m := mkRat (2822251) 125000
  M3 := mkRat (1746013) 100000
  b := mkRat (1) 100
  T := mkRat (-28551937) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1135819) 200000
  bi := mkRat (-341213) 1000000
  tr := mkRat (536219) 200000
  ti := mkRat (-215213) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (85137) 250000
  ply := mkRat (-53803) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (1147) 12500
  na := mkRat (-22963) 500000
  nb := mkRat (-31217) 31250
  K := mkRat (80001) 1000

/-- The certificate data for `r = 125`. -/
def d125 : SmData where
  ur := mkRat (83609689485921) 20000000000000
  ui := mkRat (-27377757969457) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (31) 500
  V := mkRat (750141) 500000
  m := mkRat (22944009) 1000000
  M3 := mkRat (3547683) 200000
  b := mkRat (1) 100
  T := mkRat (-14508007) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1419871) 250000
  bi := mkRat (-167889) 500000
  tr := mkRat (670371) 250000
  ti := mkRat (-105889) 500000
  rs := mkRat (1) 500000
  plx := mkRat (170371) 500000
  ply := mkRat (-105889) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (9029) 100000
  na := mkRat (-45191) 1000000
  nb := mkRat (-499489) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 127`. -/
def d127 : SmData where
  ur := mkRat (104521409687429) 25000000000000
  ui := mkRat (-842127745029) 3125000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (61) 1000
  V := mkRat (1500241) 1000000
  m := mkRat (932401) 40000
  M3 := mkRat (18016773) 1000000
  b := mkRat (1) 100
  T := mkRat (-7370023) 250
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (354991) 62500
  bi := mkRat (-330481) 1000000
  tr := mkRat (41904) 15625
  ti := mkRat (-208481) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (5327) 15625
  ply := mkRat (-1303) 12500
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (1111) 12500
  na := mkRat (-8897) 200000
  nb := mkRat (-99901) 100000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 129`. -/
def d129 : SmData where
  ur := mkRat (209060571750411) 50000000000000
  ui := mkRat (-26531675946931) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (3) 50
  V := mkRat (1500201) 1000000
  m := mkRat (23676057) 1000000
  M3 := mkRat (9147601) 500000
  b := mkRat (1) 100
  T := mkRat (-2994417) 100
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5680211) 1000000
  bi := mkRat (-325317) 1000000
  tr := mkRat (2682211) 1000000
  ti := mkRat (-205317) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (170553) 500000
  ply := mkRat (-51329) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (547) 6250
  na := mkRat (-1369) 31250
  nb := mkRat (-999039) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 131`. -/
def d131 : SmData where
  ur := mkRat (52269382854623) 12500000000000
  ui := mkRat (-13063959420061) 50000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (59) 1000
  V := mkRat (1500161) 1000000
  m := mkRat (12021051) 500000
  M3 := mkRat (3714737) 200000
  b := mkRat (1) 100
  T := mkRat (-3801031) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5680551) 1000000
  bi := mkRat (-320279) 1000000
  tr := mkRat (2682551) 1000000
  ti := mkRat (-202279) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (85319) 250000
  ply := mkRat (-5057) 50000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4311) 50000
  na := mkRat (-21579) 500000
  nb := mkRat (-249767) 250000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 133`. -/
def d133 : SmData where
  ur := mkRat (418187490422021) 100000000000000
  ui := mkRat (-12868124547509) 50000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (29) 500
  V := mkRat (750061) 500000
  m := mkRat (24408161) 1000000
  M3 := mkRat (2356529) 125000
  b := mkRat (1) 100
  T := mkRat (-15436163) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (45447) 8000
  bi := mkRat (-157681) 500000
  tr := mkRat (21463) 8000
  ti := mkRat (-99681) 500000
  rs := mkRat (1) 500000
  plx := mkRat (170719) 500000
  ply := mkRat (-99681) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4249) 50000
  na := mkRat (-21267) 500000
  nb := mkRat (-199819) 200000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 135`. -/
def d135 : SmData where
  ur := mkRat (83643702617209) 20000000000000
  ui := mkRat (-3169516582929) 12500000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (29) 500
  V := mkRat (750061) 500000
  m := mkRat (24774233) 1000000
  M3 := mkRat (19131373) 1000000
  b := mkRat (1) 100
  T := mkRat (-6267281) 200
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1136237) 200000
  bi := mkRat (-311561) 1000000
  tr := mkRat (536637) 200000
  ti := mkRat (-195561) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (42699) 125000
  ply := mkRat (-4889) 50000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (1667) 20000
  na := mkRat (-41721) 1000000
  nb := mkRat (-999129) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 137`. -/
def d137 : SmData where
  ur := mkRat (418248211415787) 100000000000000
  ui := mkRat (-4997413291841) 20000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (57) 1000
  V := mkRat (375021) 250000
  m := mkRat (25140317) 1000000
  M3 := mkRat (3882007) 200000
  b := mkRat (1) 100
  T := mkRat (-6360097) 200
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2840741) 500000
  bi := mkRat (-306871) 1000000
  tr := mkRat (1341741) 500000
  ti := mkRat (-192871) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (341741) 1000000
  ply := mkRat (-24109) 250000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (411) 5000
  na := mkRat (-20573) 500000
  nb := mkRat (-999153) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 139`. -/
def d139 : SmData where
  ur := mkRat (418276660286253) 100000000000000
  ui := mkRat (-24628576149387) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (7) 125
  V := mkRat (750023) 500000
  m := mkRat (25506413) 1000000
  M3 := mkRat (984437) 50000
  b := mkRat (1) 100
  T := mkRat (-6452913) 200
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5681767) 1000000
  bi := mkRat (-151143) 500000
  tr := mkRat (2683767) 1000000
  ti := mkRat (-95143) 500000
  rs := mkRat (1) 500000
  plx := mkRat (85471) 250000
  ply := mkRat (-95143) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (811) 10000
  na := mkRat (-40593) 1000000
  nb := mkRat (-39967) 40000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 141`. -/
def d141 : SmData where
  ur := mkRat (209151964670137) 50000000000000
  ui := mkRat (-24280214131609) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (11) 200
  V := mkRat (1500009) 1000000
  m := mkRat (25872521) 1000000
  M3 := mkRat (7987) 400
  b := mkRat (1) 100
  T := mkRat (-6545729) 200
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5682039) 1000000
  bi := mkRat (-148901) 500000
  tr := mkRat (2684039) 1000000
  ti := mkRat (-93901) 500000
  rs := mkRat (1) 500000
  plx := mkRat (342019) 1000000
  ply := mkRat (-93901) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (2001) 25000
  na := mkRat (-40061) 1000000
  nb := mkRat (-999197) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 143`. -/
def d143 : SmData where
  ur := mkRat (418330083421713) 100000000000000
  ui := mkRat (-2992694709951) 12500000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (27) 500
  V := mkRat (1499973) 1000000
  m := mkRat (26238639) 1000000
  M3 := mkRat (20246313) 1000000
  b := mkRat (1) 100
  T := mkRat (-1327709) 40
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5682301) 1000000
  bi := mkRat (-36677) 125000
  tr := mkRat (2684301) 1000000
  ti := mkRat (-23177) 125000
  rs := mkRat (1) 500000
  plx := mkRat (6843) 20000
  ply := mkRat (-23177) 250000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (3951) 50000
  na := mkRat (-39551) 1000000
  nb := mkRat (-999217) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 145`. -/
def d145 : SmData where
  ur := mkRat (52294397870921) 12500000000000
  ui := mkRat (-590305181021) 2500000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (27) 500
  V := mkRat (1499973) 1000000
  m := mkRat (831399) 31250
  M3 := mkRat (2565713) 125000
  b := mkRat (1) 100
  T := mkRat (-6731361) 200
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (710319) 125000
  bi := mkRat (-145061) 500000
  tr := mkRat (335569) 125000
  ti := mkRat (-91061) 500000
  rs := mkRat (1) 500000
  plx := mkRat (85569) 250000
  ply := mkRat (-91061) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (7761) 100000
  na := mkRat (-38847) 1000000
  nb := mkRat (-199849) 200000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 147`. -/
def d147 : SmData where
  ur := mkRat (52297410545253) 12500000000000
  ui := mkRat (-11645892435917) 50000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (53) 1000
  V := mkRat (1499937) 1000000
  m := mkRat (26970907) 1000000
  M3 := mkRat (4160919) 200000
  b := mkRat (1) 100
  T := mkRat (-17060443) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5682793) 1000000
  bi := mkRat (-142959) 500000
  tr := mkRat (2684793) 1000000
  ti := mkRat (-89959) 500000
  rs := mkRat (1) 500000
  plx := mkRat (85599) 250000
  ply := mkRat (-89959) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (7667) 100000
  na := mkRat (-4797) 125000
  nb := mkRat (-999263) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 149`. -/
def d149 : SmData where
  ur := mkRat (104600610065139) 25000000000000
  ui := mkRat (-4595986559699) 20000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (13) 250
  V := mkRat (749951) 500000
  m := mkRat (5467411) 200000
  M3 := mkRat (4216707) 200000
  b := mkRat (1) 100
  T := mkRat (-34584967) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (355189) 62500
  bi := mkRat (-281799) 1000000
  tr := mkRat (83907) 31250
  ti := mkRat (-177799) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (21407) 62500
  ply := mkRat (-889) 10000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (7577) 100000
  na := mkRat (-37923) 1000000
  nb := mkRat (-12491) 12500
  K := mkRat (80001) 1000

/-- The certificate data for `r = 151`. -/
def d151 : SmData where
  ur := mkRat (418424699880529) 100000000000000
  ui := mkRat (-22676312089849) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (13) 250
  V := mkRat (749951) 500000
  m := mkRat (27703213) 1000000
  M3 := mkRat (5340763) 250000
  b := mkRat (1) 100
  T := mkRat (-35049049) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5683247) 1000000
  bi := mkRat (-278763) 1000000
  tr := mkRat (2685247) 1000000
  ti := mkRat (-174763) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (342623) 1000000
  ply := mkRat (-43691) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (7447) 100000
  na := mkRat (-1491) 40000
  nb := mkRat (-199861) 200000
  K := mkRat (80001) 1000

theorem ok123 : famCertOK 123 d123 = true := by
  decide +kernel

theorem ok125 : famCertOK 125 d125 = true := by
  decide +kernel

theorem ok127 : famCertOK 127 d127 = true := by
  decide +kernel

theorem ok129 : famCertOK 129 d129 = true := by
  decide +kernel

theorem ok131 : famCertOK 131 d131 = true := by
  decide +kernel

theorem ok133 : famCertOK 133 d133 = true := by
  decide +kernel

theorem ok135 : famCertOK 135 d135 = true := by
  decide +kernel

theorem ok137 : famCertOK 137 d137 = true := by
  decide +kernel

theorem ok139 : famCertOK 139 d139 = true := by
  decide +kernel

theorem ok141 : famCertOK 141 d141 = true := by
  decide +kernel

theorem ok143 : famCertOK 143 d143 = true := by
  decide +kernel

theorem ok145 : famCertOK 145 d145 = true := by
  decide +kernel

theorem ok147 : famCertOK 147 d147 = true := by
  decide +kernel

theorem ok149 : famCertOK 149 d149 = true := by
  decide +kernel

theorem ok151 : famCertOK 151 d151 = true := by
  decide +kernel

/-- The data of chunk 5. -/
def chunk5 : List (ℕ × SmData) :=
  [(123, d123), (125, d125), (127, d127), (129, d129), (131, d131), (133, d133), (135, d135), (137, d137), (139, d139), (141, d141), (143, d143), (145, d145), (147, d147), (149, d149), (151, d151)]

theorem chunk5_ok : ∀ p ∈ chunk5, famCertOK p.1 p.2 = true :=
  List.forall_mem_cons.2 ⟨ok123,
    List.forall_mem_cons.2 ⟨ok125,
    List.forall_mem_cons.2 ⟨ok127,
    List.forall_mem_cons.2 ⟨ok129,
    List.forall_mem_cons.2 ⟨ok131,
    List.forall_mem_cons.2 ⟨ok133,
    List.forall_mem_cons.2 ⟨ok135,
    List.forall_mem_cons.2 ⟨ok137,
    List.forall_mem_cons.2 ⟨ok139,
    List.forall_mem_cons.2 ⟨ok141,
    List.forall_mem_cons.2 ⟨ok143,
    List.forall_mem_cons.2 ⟨ok145,
    List.forall_mem_cons.2 ⟨ok147,
    List.forall_mem_cons.2 ⟨ok149,
    List.forall_mem_cons.2 ⟨ok151,
    List.forall_mem_nil _⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩

end OddZeta.Small
