import OddZeta.Family.SmallMach

/-!
# Per-`r` certificate data and kernel checks, chunk 8: `r ∈ {213, 215, 217, 219, 221, 223, 225, 227, 229, 231, 233, 235, 237, 239, 241}`

Generated by `scripts/small_cert_gen.py`.
-/

set_option linter.style.longLine false

namespace OddZeta.Small

/-- The certificate data for `r = 213`. -/
def d213 : SmData where
  ur := mkRat (654435420351) 156250000000
  ui := mkRat (-16085665911083) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (37) 1000
  V := mkRat (1500457) 1000000
  m := mkRat (19528631) 500000
  M3 := mkRat (751391) 25000
  b := mkRat (1) 100
  T := mkRat (-24717831) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5688387) 1000000
  bi := mkRat (-197857) 1000000
  tr := mkRat (2688387) 1000000
  ti := mkRat (-123857) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (172097) 500000
  ply := mkRat (-7741) 125000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (1319) 25000
  na := mkRat (-3301) 125000
  nb := mkRat (-999651) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 215`. -/
def d215 : SmData where
  ur := mkRat (83769304687859) 20000000000000
  ui := mkRat (-7968110790217) 50000000000000
  vr := mkRat (-3) 2
  vi := mkRat (9) 250
  V := mkRat (93777) 62500
  m := mkRat (4927949) 125000
  M3 := mkRat (6067111) 200000
  b := mkRat (1) 100
  T := mkRat (-12474937) 250
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1137693) 200000
  bi := mkRat (-97681) 500000
  tr := mkRat (537693) 200000
  ti := mkRat (-61681) 500000
  rs := mkRat (1) 500000
  plx := mkRat (43029) 125000
  ply := mkRat (-61681) 1000000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (1051) 20000
  na := mkRat (-13151) 500000
  nb := mkRat (-499827) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 217`. -/
def d217 : SmData where
  ur := mkRat (26178385457241) 6250000000000
  ui := mkRat (-15789527064087) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (9) 250
  V := mkRat (93777) 62500
  m := mkRat (1591597) 40000
  M3 := mkRat (15308017) 500000
  b := mkRat (1) 100
  T := mkRat (-25181917) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2844271) 500000
  bi := mkRat (-38779) 200000
  tr := mkRat (1344271) 500000
  ti := mkRat (-24379) 200000
  rs := mkRat (1) 500000
  plx := mkRat (344271) 1000000
  ply := mkRat (-15237) 250000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (649) 12500
  na := mkRat (-25989) 1000000
  nb := mkRat (-499831) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 219`. -/
def d219 : SmData where
  ur := mkRat (209430804101747) 50000000000000
  ui := mkRat (-3129101439447) 20000000000000
  vr := mkRat (-3) 2
  vi := mkRat (9) 250
  V := mkRat (93777) 62500
  m := mkRat (20078131) 500000
  M3 := mkRat (30896527) 1000000
  b := mkRat (1) 100
  T := mkRat (-50827921) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (711077) 125000
  bi := mkRat (-38491) 200000
  tr := mkRat (336077) 125000
  ti := mkRat (-24091) 200000
  rs := mkRat (1) 500000
  plx := mkRat (86077) 250000
  ply := mkRat (-15057) 250000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (5131) 100000
  na := mkRat (-12841) 500000
  nb := mkRat (-99967) 100000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 221`. -/
def d221 : SmData where
  ur := mkRat (83773770662879) 20000000000000
  ui := mkRat (-15504089528397) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (7) 200
  V := mkRat (1500409) 1000000
  m := mkRat (40522601) 1000000
  M3 := mkRat (3117651) 100000
  b := mkRat (1) 100
  T := mkRat (-51292007) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5688689) 1000000
  bi := mkRat (-190041) 1000000
  tr := mkRat (2688689) 1000000
  ti := mkRat (-120041) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (68869) 200000
  ply := mkRat (-3001) 50000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (5113) 100000
  na := mkRat (-25593) 1000000
  nb := mkRat (-124959) 125000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 223`. -/
def d223 : SmData where
  ur := mkRat (418875909541697) 100000000000000
  ui := mkRat (-15365204198141) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (7) 200
  V := mkRat (1500409) 1000000
  m := mkRat (40888943) 1000000
  M3 := mkRat (15728513) 500000
  b := mkRat (1) 100
  T := mkRat (-25878047) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5688759) 1000000
  bi := mkRat (-47163) 250000
  tr := mkRat (2688759) 1000000
  ti := mkRat (-29663) 250000
  rs := mkRat (1) 500000
  plx := mkRat (17219) 50000
  ply := mkRat (-29663) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (2527) 50000
  na := mkRat (-25297) 1000000
  nb := mkRat (-999679) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 225`. -/
def d225 : SmData where
  ur := mkRat (209441391738157) 50000000000000
  ui := mkRat (-15228783824251) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (7) 200
  V := mkRat (1500409) 1000000
  m := mkRat (5156911) 125000
  M3 := mkRat (7934389) 250000
  b := mkRat (1) 100
  T := mkRat (-52220181) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1422207) 250000
  bi := mkRat (-23411) 125000
  tr := mkRat (672207) 250000
  ti := mkRat (-14661) 125000
  rs := mkRat (1) 500000
  plx := mkRat (172207) 500000
  ply := mkRat (-14661) 250000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (1249) 25000
  na := mkRat (-12503) 500000
  nb := mkRat (-999687) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 227`. -/
def d227 : SmData where
  ur := mkRat (20944474071137) 5000000000000
  ui := mkRat (-7547381696471) 50000000000000
  vr := mkRat (-3) 2
  vi := mkRat (17) 500
  V := mkRat (750193) 500000
  m := mkRat (10405409) 250000
  M3 := mkRat (800439) 25000
  b := mkRat (1) 100
  T := mkRat (-52684267) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1137779) 200000
  bi := mkRat (-46237) 250000
  tr := mkRat (537779) 200000
  ti := mkRat (-29237) 250000
  rs := mkRat (1) 500000
  plx := mkRat (5382) 15625
  ply := mkRat (-29237) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4981) 100000
  na := mkRat (-24933) 1000000
  nb := mkRat (-999689) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 229`. -/
def d229 : SmData where
  ur := mkRat (418896009413893) 100000000000000
  ui := mkRat (-2992616031151) 20000000000000
  vr := mkRat (-3) 2
  vi := mkRat (17) 500
  V := mkRat (750193) 500000
  m := mkRat (20993993) 500000
  M3 := mkRat (32298111) 1000000
  b := mkRat (1) 100
  T := mkRat (-26574177) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (17778) 3125
  bi := mkRat (-183631) 1000000
  tr := mkRat (8403) 3125
  ti := mkRat (-115631) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (2153) 6250
  ply := mkRat (-7227) 125000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (197) 4000
  na := mkRat (-6163) 250000
  nb := mkRat (-62481) 62500
  K := mkRat (80001) 1000

/-- The certificate data for `r = 231`. -/
def d231 : SmData where
  ur := mkRat (83780474645013) 20000000000000
  ui := mkRat (-14833673531793) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (17) 500
  V := mkRat (750193) 500000
  m := mkRat (21177169) 500000
  M3 := mkRat (32578673) 1000000
  b := mkRat (1) 100
  T := mkRat (-53612441) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (88891) 15625
  bi := mkRat (-182337) 1000000
  tr := mkRat (42016) 15625
  ti := mkRat (-114337) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (5383) 15625
  ply := mkRat (-3573) 62500
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (487) 10000
  na := mkRat (-3047) 125000
  nb := mkRat (-499851) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 233`. -/
def d233 : SmData where
  ur := mkRat (52363572298381) 12500000000000
  ui := mkRat (-14706485014967) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (33) 1000
  V := mkRat (1500363) 1000000
  m := mkRat (21360347) 500000
  M3 := mkRat (4107337) 125000
  b := mkRat (1) 100
  T := mkRat (-6759566) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2844543) 500000
  bi := mkRat (-36013) 200000
  tr := mkRat (1344543) 500000
  ti := mkRat (-22813) 200000
  rs := mkRat (1) 500000
  plx := mkRat (344543) 1000000
  ply := mkRat (-7129) 125000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (2429) 50000
  na := mkRat (-12159) 500000
  nb := mkRat (-124963) 125000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 235`. -/
def d235 : SmData where
  ur := mkRat (209457315099239) 50000000000000
  ui := mkRat (-14581458085967) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (33) 1000
  V := mkRat (1500363) 1000000
  m := mkRat (43087051) 1000000
  M3 := mkRat (33139277) 1000000
  b := mkRat (1) 100
  T := mkRat (-10908123) 200
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2844573) 500000
  bi := mkRat (-35763) 200000
  tr := mkRat (1344573) 500000
  ti := mkRat (-22563) 200000
  rs := mkRat (1) 500000
  plx := mkRat (344573) 1000000
  ply := mkRat (-7051) 125000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (961) 20000
  na := mkRat (-6013) 250000
  nb := mkRat (-99971) 100000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 237`. -/
def d237 : SmData where
  ur := mkRat (83784106747493) 20000000000000
  ui := mkRat (-3614634532169) 25000000000000
  vr := mkRat (-3) 2
  vi := mkRat (33) 1000
  V := mkRat (1500363) 1000000
  m := mkRat (43453411) 1000000
  M3 := mkRat (3341987) 100000
  b := mkRat (1) 100
  T := mkRat (-27502351) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1137841) 200000
  bi := mkRat (-35517) 200000
  tr := mkRat (537841) 200000
  ti := mkRat (-22317) 200000
  rs := mkRat (1) 500000
  plx := mkRat (172301) 500000
  ply := mkRat (-3487) 62500
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4753) 100000
  na := mkRat (-23789) 1000000
  nb := mkRat (-249929) 250000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 239`. -/
def d239 : SmData where
  ur := mkRat (13091446683517) 3125000000000
  ui := mkRat (-14337672350767) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (33) 1000
  V := mkRat (1500363) 1000000
  m := mkRat (21909887) 500000
  M3 := mkRat (16850237) 500000
  b := mkRat (1) 100
  T := mkRat (-55468789) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5689263) 1000000
  bi := mkRat (-176377) 1000000
  tr := mkRat (2689263) 1000000
  ti := mkRat (-110377) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (43079) 125000
  ply := mkRat (-13797) 250000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4701) 100000
  na := mkRat (-23531) 1000000
  nb := mkRat (-999723) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 241`. -/
def d241 : SmData where
  ur := mkRat (418931915272991) 100000000000000
  ui := mkRat (-1777351213529) 12500000000000
  vr := mkRat (-3) 2
  vi := mkRat (4) 125
  V := mkRat (750171) 500000
  m := mkRat (22093069) 500000
  M3 := mkRat (4247571) 125000
  b := mkRat (1) 100
  T := mkRat (-55932877) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5689319) 1000000
  bi := mkRat (-43547) 250000
  tr := mkRat (2689319) 1000000
  ti := mkRat (-27547) 250000
  rs := mkRat (1) 500000
  plx := mkRat (344659) 1000000
  ply := mkRat (-27547) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4693) 100000
  na := mkRat (-23491) 1000000
  nb := mkRat (-249931) 250000
  K := mkRat (80001) 1000

/-- The data of chunk 8. -/
def chunk8 : List (ℕ × SmData) :=
  [(213, d213), (215, d215), (217, d217), (219, d219), (221, d221), (223, d223), (225, d225), (227, d227), (229, d229), (231, d231), (233, d233), (235, d235), (237, d237), (239, d239), (241, d241)]

theorem chunk8_ok : chunk8.all (fun p => famCertOK p.1 p.2) = true := by
  decide +kernel

end OddZeta.Small
