import OddZeta.Family.SmallMach

/-!
# Per-`r` certificate data and kernel checks, chunk 7: `r ∈ {183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207, 209, 211}`

Generated by `scripts/small_cert_gen.py`.
-/

set_option linter.style.longLine false

namespace OddZeta.Small

/-- The certificate data for `r = 183`. -/
def d183 : SmData where
  ur := mkRat (209344580407467) 50000000000000
  ui := mkRat (-18718440417469) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (43) 1000
  V := mkRat (1499617) 1000000
  m := mkRat (4195343) 125000
  M3 := mkRat (25834859) 1000000
  b := mkRat (1) 100
  T := mkRat (-2123719) 50
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1421473) 250000
  bi := mkRat (-28773) 125000
  tr := mkRat (671973) 250000
  ti := mkRat (-18023) 125000
  rs := mkRat (1) 500000
  plx := mkRat (171973) 500000
  ply := mkRat (-18023) 250000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (3071) 50000
  na := mkRat (-15371) 500000
  nb := mkRat (-999527) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 185`. -/
def d185 : SmData where
  ur := mkRat (418701379986933) 100000000000000
  ui := mkRat (-18516418584121) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (21) 500
  V := mkRat (1499589) 1000000
  m := mkRat (4241127) 125000
  M3 := mkRat (13057169) 500000
  b := mkRat (1) 100
  T := mkRat (-8587693) 200
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2843007) 500000
  bi := mkRat (-56791) 250000
  tr := mkRat (1344007) 500000
  ti := mkRat (-35791) 250000
  rs := mkRat (1) 500000
  plx := mkRat (344007) 1000000
  ply := mkRat (-35791) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (3049) 50000
  na := mkRat (-7631) 250000
  nb := mkRat (-499767) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 187`. -/
def d187 : SmData where
  ur := mkRat (209356609078417) 50000000000000
  ui := mkRat (-9159353907953) 50000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (21) 500
  V := mkRat (1499589) 1000000
  m := mkRat (8573823) 250000
  M3 := mkRat (26394369) 1000000
  b := mkRat (1) 100
  T := mkRat (-43402549) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1421533) 250000
  bi := mkRat (-225187) 1000000
  tr := mkRat (672033) 250000
  ti := mkRat (-141187) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (172033) 500000
  ply := mkRat (-35297) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (3007) 50000
  na := mkRat (-15051) 500000
  nb := mkRat (-499773) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 189`. -/
def d189 : SmData where
  ur := mkRat (418724691166111) 100000000000000
  ui := mkRat (-906258583543) 5000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (41) 1000
  V := mkRat (1499561) 1000000
  m := mkRat (34661573) 1000000
  M3 := mkRat (6668469) 250000
  b := mkRat (1) 100
  T := mkRat (-21933317) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5686247) 1000000
  bi := mkRat (-55563) 250000
  tr := mkRat (2688247) 1000000
  ti := mkRat (-35063) 250000
  rs := mkRat (1) 500000
  plx := mkRat (86031) 250000
  ply := mkRat (-35063) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (2987) 50000
  na := mkRat (-14951) 500000
  nb := mkRat (-15618) 15625
  K := mkRat (80001) 1000

/-- The certificate data for `r = 191`. -/
def d191 : SmData where
  ur := mkRat (418735814038027) 100000000000000
  ui := mkRat (-1120979962543) 6250000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (41) 1000
  V := mkRat (1499561) 1000000
  m := mkRat (35027859) 1000000
  M3 := mkRat (13476973) 500000
  b := mkRat (1) 100
  T := mkRat (-44330719) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2843179) 500000
  bi := mkRat (-220357) 1000000
  tr := mkRat (1344179) 500000
  ti := mkRat (-138357) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (344179) 1000000
  ply := mkRat (-34589) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (5893) 100000
  na := mkRat (-29497) 1000000
  nb := mkRat (-249891) 250000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 193`. -/
def d193 : SmData where
  ur := mkRat (104686650256981) 25000000000000
  ui := mkRat (-17750105657039) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (1) 25
  V := mkRat (749767) 500000
  m := mkRat (35394149) 1000000
  M3 := mkRat (27233499) 1000000
  b := mkRat (1) 100
  T := mkRat (-11198701) 250
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2843233) 500000
  bi := mkRat (-217501) 1000000
  tr := mkRat (1344233) 500000
  ti := mkRat (-137501) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (344233) 1000000
  ply := mkRat (-11) 160
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (183) 3125
  na := mkRat (-14657) 500000
  nb := mkRat (-99957) 100000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 195`. -/
def d195 : SmData where
  ur := mkRat (83751413133989) 20000000000000
  ui := mkRat (-2196041276971) 12500000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (1) 25
  V := mkRat (749767) 500000
  m := mkRat (35760443) 1000000
  M3 := mkRat (5502721) 200000
  b := mkRat (1) 100
  T := mkRat (-4525889) 100
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5686571) 1000000
  bi := mkRat (-215683) 1000000
  tr := mkRat (2688571) 1000000
  ti := mkRat (-135683) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (172143) 500000
  ply := mkRat (-33921) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (5779) 100000
  na := mkRat (-28927) 1000000
  nb := mkRat (-999581) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 197`. -/
def d197 : SmData where
  ur := mkRat (83753444164093) 20000000000000
  ui := mkRat (-17390237717903) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (39) 1000
  V := mkRat (374877) 250000
  m := mkRat (36126741) 1000000
  M3 := mkRat (27793203) 1000000
  b := mkRat (1) 100
  T := mkRat (-1828919) 40
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (355417) 62500
  bi := mkRat (-106451) 500000
  tr := mkRat (84021) 31250
  ti := mkRat (-67451) 500000
  rs := mkRat (1) 500000
  plx := mkRat (21521) 62500
  ply := mkRat (-67451) 1000000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (2873) 50000
  na := mkRat (-28759) 1000000
  nb := mkRat (-499793) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 199`. -/
def d199 : SmData where
  ur := mkRat (418777078698499) 100000000000000
  ui := mkRat (-17215717426167) 100000000000000
  vr := mkRat (-1499) 1000
  vi := mkRat (39) 1000
  V := mkRat (374877) 250000
  m := mkRat (36493043) 1000000
  M3 := mkRat (28073343) 1000000
  b := mkRat (1) 100
  T := mkRat (-2309353) 50
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5686771) 1000000
  bi := mkRat (-211157) 1000000
  tr := mkRat (2688771) 1000000
  ti := mkRat (-133157) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (172193) 500000
  ply := mkRat (-33289) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (5671) 100000
  na := mkRat (-28387) 1000000
  nb := mkRat (-249899) 250000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 201`. -/
def d201 : SmData where
  ur := mkRat (418786650923327) 100000000000000
  ui := mkRat (-17044662995967) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (39) 1000
  V := mkRat (1500507) 1000000
  m := mkRat (36859349) 1000000
  M3 := mkRat (141871) 5000
  b := mkRat (1) 100
  T := mkRat (-23325573) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5687867) 1000000
  bi := mkRat (-209447) 1000000
  tr := mkRat (2687867) 1000000
  ti := mkRat (-131447) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (343933) 1000000
  ply := mkRat (-16431) 250000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (7) 125
  na := mkRat (-28029) 1000000
  nb := mkRat (-999607) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 203`. -/
def d203 : SmData where
  ur := mkRat (418795948549543) 100000000000000
  ui := mkRat (-16876972259849) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (19) 500
  V := mkRat (750241) 500000
  m := mkRat (37225659) 1000000
  M3 := mkRat (28654057) 1000000
  b := mkRat (1) 100
  T := mkRat (-5889404) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5687959) 1000000
  bi := mkRat (-20677) 100000
  tr := mkRat (2687959) 1000000
  ti := mkRat (-13077) 100000
  rs := mkRat (1) 500000
  plx := mkRat (17199) 50000
  ply := mkRat (-13077) 200000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (5571) 100000
  na := mkRat (-6971) 250000
  nb := mkRat (-999611) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 205`. -/
def d205 : SmData where
  ur := mkRat (418804982099743) 100000000000000
  ui := mkRat (-16712547024531) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (19) 500
  V := mkRat (750241) 500000
  m := mkRat (37591973) 1000000
  M3 := mkRat (578689) 20000
  b := mkRat (1) 100
  T := mkRat (-47579317) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (113761) 20000
  bi := mkRat (-1641) 8000
  tr := mkRat (53761) 20000
  ti := mkRat (-1033) 8000
  rs := mkRat (1) 500000
  plx := mkRat (13761) 40000
  ply := mkRat (-32281) 500000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (11) 200
  na := mkRat (-6883) 250000
  nb := mkRat (-49981) 50000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 207`. -/
def d207 : SmData where
  ur := mkRat (418813761595019) 100000000000000
  ui := mkRat (-16551292879629) 100000000000000
  vr := mkRat (-3) 2
  vi := mkRat (19) 500
  V := mkRat (750241) 500000
  m := mkRat (3795829) 100000
  M3 := mkRat (1460743) 50000
  b := mkRat (1) 100
  T := mkRat (-48043403) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2844069) 500000
  bi := mkRat (-203513) 1000000
  tr := mkRat (1344069) 500000
  ti := mkRat (-127513) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (344069) 1000000
  ply := mkRat (-15939) 250000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (679) 12500
  na := mkRat (-6797) 250000
  nb := mkRat (-99963) 100000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 209`. -/
def d209 : SmData where
  ur := mkRat (52352787072929) 12500000000000
  ui := mkRat (-8196559508669) 50000000000000
  vr := mkRat (-3) 2
  vi := mkRat (37) 1000
  V := mkRat (1500457) 1000000
  m := mkRat (38324611) 1000000
  M3 := mkRat (7373687) 250000
  b := mkRat (1) 100
  T := mkRat (-48507489) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5688223) 1000000
  bi := mkRat (-200931) 1000000
  tr := mkRat (2688223) 1000000
  ti := mkRat (-126931) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (344111) 1000000
  ply := mkRat (-12693) 200000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (5407) 100000
  na := mkRat (-3383) 125000
  nb := mkRat (-999633) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 211`. -/
def d211 : SmData where
  ur := mkRat (209415298083307) 50000000000000
  ui := mkRat (-1623793806231) 10000000000000
  vr := mkRat (-3) 2
  vi := mkRat (37) 1000
  V := mkRat (1500457) 1000000
  m := mkRat (19345467) 500000
  M3 := mkRat (14887593) 500000
  b := mkRat (1) 100
  T := mkRat (-1958863) 40
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2844153) 500000
  bi := mkRat (-199379) 1000000
  tr := mkRat (1344153) 500000
  ti := mkRat (-125379) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (344153) 1000000
  ply := mkRat (-62689) 1000000
  lam := mkRat (1) 4
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (5341) 100000
  na := mkRat (-26733) 1000000
  nb := mkRat (-499821) 500000
  K := mkRat (80001) 1000

/-- The data of chunk 7. -/
def chunk7 : List (ℕ × SmData) :=
  [(183, d183), (185, d185), (187, d187), (189, d189), (191, d191), (193, d193), (195, d195), (197, d197), (199, d199), (201, d201), (203, d203), (205, d205), (207, d207), (209, d209), (211, d211)]

theorem chunk7_ok : chunk7.all (fun p => famCertOK p.1 p.2) = true := by
  decide +kernel

end OddZeta.Small
