import OddZeta.Family.SmallMach

/-!
# Per-`r` certificate data and kernel checks, chunk 2: `r ∈ {33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61}`

Generated by `scripts/small_cert_gen.py`.
-/

set_option linter.style.longLine false

namespace OddZeta.Small

/-- The certificate data for `r = 33`. -/
def d33 : SmData where
  ur := mkRat (80583346166453) 20000000000000
  ui := mkRat (-101461034296377) 100000000000000
  vr := mkRat (-741) 500
  vi := mkRat (233) 1000
  V := mkRat (300041) 200000
  m := mkRat (3084551) 500000
  M3 := mkRat (2466803) 500000
  b := mkRat (1) 100
  T := mkRat (-958774) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5511167) 1000000
  bi := mkRat (-124761) 100000
  tr := mkRat (2547167) 1000000
  ti := mkRat (-78161) 100000
  rs := mkRat (1) 500000
  plx := mkRat (17099) 62500
  ply := mkRat (-78161) 200000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-33881) 200000
  nb := mkRat (-492773) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 35`. -/
def d35 : SmData where
  ur := mkRat (404677322942681) 100000000000000
  ui := mkRat (-95906989151353) 100000000000000
  vr := mkRat (-371) 250
  vi := mkRat (11) 50
  V := mkRat (1500219) 1000000
  m := mkRat (6529199) 1000000
  M3 := mkRat (5252273) 1000000
  b := mkRat (1) 100
  T := mkRat (-8134103) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5530773) 1000000
  bi := mkRat (-117907) 100000
  tr := mkRat (2562773) 1000000
  ti := mkRat (-73907) 100000
  rs := mkRat (1) 500000
  plx := mkRat (140693) 500000
  ply := mkRat (-73907) 200000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-79947) 500000
  nb := mkRat (-493567) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 37`. -/
def d37 : SmData where
  ur := mkRat (40616801845109) 10000000000000
  ui := mkRat (-18183658246941) 20000000000000
  vr := mkRat (-297) 200
  vi := mkRat (26) 125
  V := mkRat (1499497) 1000000
  m := mkRat (6889967) 1000000
  M3 := mkRat (557161) 100000
  b := mkRat (1) 100
  T := mkRat (-8598033) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (138667) 25000
  bi := mkRat (-1117183) 1000000
  tr := mkRat (64417) 25000
  ti := mkRat (-701183) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (14417) 50000
  ply := mkRat (-5478) 15625
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-1893) 12500
  nb := mkRat (-494233) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 39`. -/
def d39 : SmData where
  ur := mkRat (407441128809779) 100000000000000
  ui := mkRat (-43207190467233) 50000000000000
  vr := mkRat (-1487) 1000
  vi := mkRat (99) 500
  V := mkRat (12001) 8000
  m := mkRat (3625653) 500000
  M3 := mkRat (2949931) 500000
  b := mkRat (1) 100
  T := mkRat (-9061979) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5561411) 1000000
  bi := mkRat (-16596) 15625
  tr := mkRat (2587411) 1000000
  ti := mkRat (-20817) 31250
  rs := mkRat (1) 500000
  plx := mkRat (58741) 200000
  ply := mkRat (-20817) 62500
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-17963) 125000
  nb := mkRat (-49481) 50000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 41`. -/
def d41 : SmData where
  ur := mkRat (40853692571333) 10000000000000
  ui := mkRat (-8232901985461) 10000000000000
  vr := mkRat (-186) 125
  vi := mkRat (47) 250
  V := mkRat (149983) 100000
  m := mkRat (475821) 62500
  M3 := mkRat (6226911) 1000000
  b := mkRat (1) 100
  T := mkRat (-4762969) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5573369) 1000000
  bi := mkRat (-101129) 100000
  tr := mkRat (2597369) 1000000
  ti := mkRat (-63529) 100000
  rs := mkRat (1) 500000
  plx := mkRat (74671) 250000
  ply := mkRat (-63529) 200000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-34221) 250000
  nb := mkRat (-495293) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 43`. -/
def d43 : SmData where
  ur := mkRat (409486807230457) 100000000000000
  ui := mkRat (-78607309014529) 100000000000000
  vr := mkRat (-1489) 1000
  vi := mkRat (9) 50
  V := mkRat (1499841) 1000000
  m := mkRat (797539) 100000
  M3 := mkRat (162549) 25000
  b := mkRat (1) 100
  T := mkRat (-998991) 100
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1395967) 250000
  bi := mkRat (-966073) 1000000
  tr := mkRat (651467) 250000
  ti := mkRat (-606073) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (151467) 500000
  ply := mkRat (-75759) 250000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (999) 4000
  na := mkRat (-65231) 500000
  nb := mkRat (-991453) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 45`. -/
def d45 : SmData where
  ur := mkRat (410315536952859) 100000000000000
  ui := mkRat (-18800851283903) 25000000000000
  vr := mkRat (-149) 100
  vi := mkRat (43) 250
  V := mkRat (299979) 200000
  m := mkRat (4169007) 500000
  M3 := mkRat (3381063) 500000
  b := mkRat (1) 100
  T := mkRat (-2613473) 250
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (1118631) 200000
  bi := mkRat (-462017) 500000
  tr := mkRat (522631) 200000
  ti := mkRat (-290017) 500000
  rs := mkRat (1) 500000
  plx := mkRat (306577) 1000000
  ply := mkRat (-290017) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (997) 4000
  na := mkRat (-7797) 62500
  nb := mkRat (-992187) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 47`. -/
def d47 : SmData where
  ur := mkRat (205521426390509) 50000000000000
  ui := mkRat (-72078756652029) 100000000000000
  vr := mkRat (-1491) 1000
  vi := mkRat (33) 200
  V := mkRat (750051) 500000
  m := mkRat (8700961) 1000000
  M3 := mkRat (1756281) 250000
  b := mkRat (1) 100
  T := mkRat (-10917883) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5601429) 1000000
  bi := mkRat (-221447) 250000
  tr := mkRat (2619429) 1000000
  ti := mkRat (-138947) 250000
  rs := mkRat (1) 500000
  plx := mkRat (154857) 500000
  ply := mkRat (-138947) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (11933) 50000
  na := mkRat (-119453) 1000000
  nb := mkRat (-992839) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 49`. -/
def d49 : SmData where
  ur := mkRat (411684639658389) 100000000000000
  ui := mkRat (-69200729592653) 100000000000000
  vr := mkRat (-373) 250
  vi := mkRat (79) 500
  V := mkRat (1500343) 1000000
  m := mkRat (141628) 15625
  M3 := mkRat (729011) 100000
  b := mkRat (1) 100
  T := mkRat (-5690941) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2804423) 500000
  bi := mkRat (-850007) 1000000
  tr := mkRat (1312423) 500000
  ti := mkRat (-534007) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (312423) 1000000
  ply := mkRat (-66751) 250000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (22917) 100000
  na := mkRat (-57351) 500000
  nb := mkRat (-993399) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 51`. -/
def d51 : SmData where
  ur := mkRat (206126897945379) 50000000000000
  ui := mkRat (-16635382072221) 25000000000000
  vr := mkRat (-373) 250
  vi := mkRat (19) 125
  V := mkRat (1499723) 1000000
  m := mkRat (2356919) 250000
  M3 := mkRat (7551813) 1000000
  b := mkRat (1) 100
  T := mkRat (-1480736) 125
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2807269) 500000
  bi := mkRat (-163483) 200000
  tr := mkRat (1315269) 500000
  ti := mkRat (-102683) 200000
  rs := mkRat (1) 500000
  plx := mkRat (315269) 1000000
  ply := mkRat (-256707) 1000000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (22017) 100000
  na := mkRat (-551) 5000
  nb := mkRat (-993909) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 53`. -/
def d53 : SmData where
  ur := mkRat (4127608810067) 1000000000000
  ui := mkRat (-3203867043379) 5000000000000
  vr := mkRat (-1493) 1000
  vi := mkRat (73) 500
  V := mkRat (750061) 500000
  m := mkRat (9791383) 1000000
  M3 := mkRat (3910277) 500000
  b := mkRat (1) 100
  T := mkRat (-12309901) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5620609) 1000000
  bi := mkRat (-786773) 1000000
  tr := mkRat (2634609) 1000000
  ti := mkRat (-494773) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (63461) 200000
  ply := mkRat (-123693) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (21209) 100000
  na := mkRat (-13269) 125000
  nb := mkRat (-994349) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 55`. -/
def d55 : SmData where
  ur := mkRat (82642921154011) 20000000000000
  ui := mkRat (-2471506301039) 4000000000000
  vr := mkRat (-1493) 1000
  vi := mkRat (141) 1000
  V := mkRat (374911) 250000
  m := mkRat (10155291) 1000000
  M3 := mkRat (1617061) 200000
  b := mkRat (1) 100
  T := mkRat (-12773919) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2812573) 500000
  bi := mkRat (-758877) 1000000
  tr := mkRat (1319573) 500000
  ti := mkRat (-476877) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (319573) 1000000
  ply := mkRat (-119219) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (2043) 10000
  na := mkRat (-20451) 200000
  nb := mkRat (-497379) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 57`. -/
def d57 : SmData where
  ur := mkRat (413622206717047) 100000000000000
  ui := mkRat (-59654722674811) 100000000000000
  vr := mkRat (-747) 500
  vi := mkRat (17) 125
  V := mkRat (750089) 500000
  m := mkRat (5259689) 500000
  M3 := mkRat (8357197) 1000000
  b := mkRat (1) 100
  T := mkRat (-6618971) 500
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (2815111) 500000
  bi := mkRat (-732547) 1000000
  tr := mkRat (1321111) 500000
  ti := mkRat (-460547) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (321111) 1000000
  ply := mkRat (-115137) 500000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (4931) 25000
  na := mkRat (-98723) 1000000
  nb := mkRat (-497557) 500000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 59`. -/
def d59 : SmData where
  ur := mkRat (413989735238623) 100000000000000
  ui := mkRat (-57663091600219) 100000000000000
  vr := mkRat (-747) 500
  vi := mkRat (131) 1000
  V := mkRat (1499733) 1000000
  m := mkRat (5441813) 500000
  M3 := mkRat (4311959) 500000
  b := mkRat (1) 100
  T := mkRat (-13701969) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5633897) 1000000
  bi := mkRat (-707631) 1000000
  tr := mkRat (2645897) 1000000
  ti := mkRat (-445631) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (322949) 1000000
  ply := mkRat (-6963) 31250
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (19077) 100000
  na := mkRat (-95481) 1000000
  nb := mkRat (-995431) 1000000
  K := mkRat (80001) 1000

/-- The certificate data for `r = 61`. -/
def d61 : SmData where
  ur := mkRat (207161141371571) 50000000000000
  ui := mkRat (-27899634667483) 50000000000000
  vr := mkRat (-299) 200
  vi := mkRat (127) 1000
  V := mkRat (300077) 200000
  m := mkRat (562401) 50000
  M3 := mkRat (8898531) 1000000
  b := mkRat (1) 100
  T := mkRat (-14166001) 1000
  m0 := (-9 : ℤ)
  yR := mkRat (-1) 4
  br := mkRat (5638223) 1000000
  bi := mkRat (-684993) 1000000
  tr := mkRat (2648223) 1000000
  ti := mkRat (-430993) 1000000
  rs := mkRat (1) 500000
  plx := mkRat (20257) 62500
  ply := mkRat (-26937) 125000
  lam := mkRat (1) 2
  gR := [mkRat (1) 2, mkRat (3) 4]
  gT := [mkRat (1) 2]
  gL := []
  c0 := mkRat (9223) 50000
  na := mkRat (-3693) 40000
  nb := mkRat (-62233) 62500
  K := mkRat (80001) 1000

/-- The data of chunk 2. -/
def chunk2 : List (ℕ × SmData) :=
  [(33, d33), (35, d35), (37, d37), (39, d39), (41, d41), (43, d43), (45, d45), (47, d47), (49, d49), (51, d51), (53, d53), (55, d55), (57, d57), (59, d59), (61, d61)]

theorem chunk2_ok : chunk2.all (fun p => famCertOK p.1 p.2) = true := by
  decide +kernel

end OddZeta.Small
