import OddZeta.Phi.DataA
import OddZeta.Phi.DataB

/-!
# The rational constant `I'`

`phiSum m K X vals = ∑_i vals[i] (∑_{k=1}^{K} (1/(k+X[i]) - 1/(k+X[i+1]))
  + [1/m ≤ X[i]] (1/X[i] - 1/X[i+1]))` (the truncation at `K` periods of the integral
`∫ φ(x) d(ψ-type weight)` of [N, (3.6)]).

The lower bounds `678.6 ≤ phiSum 72 20 XA valsA` and `774.1 ≤ phiSum 57 20 XB valsB` are proved by
a fixed-point computation in `ℕ` (scale `S = 10⁹`): every term `S (1/(k+a) - 1/(k+b))` is replaced
by the floor of its value, computed as `⌊S (dₐ n_b - d_b nₐ) / ((k dₐ + nₐ)(k d_b + n_b))⌋`
(`termLB`, `sumLB_le`).  The kernel evaluates the floors in chunks of 100 intervals
(`sumChunk`), whose values are listed in `sumChunksA`, `sumChunksB` (generated by
`scripts/phi_cert.py`).
-/

namespace OddZeta

/-- The weighted sum `I'` of the step function `vals` on the intervals of `X`. -/
def phiSum (m K : ℕ) (X : List ℚ) (vals : List ℕ) : ℚ :=
  ∑ i ∈ Finset.range (X.length - 1), (vals.getD i 0 : ℚ) *
    ((∑ k ∈ Finset.Icc 1 K, (1 / ((k : ℚ) + X.getD i 0) - 1 / ((k : ℚ) + X.getD (i + 1) 0))) +
      if (1 / m : ℚ) ≤ X.getD i 0 then 1 / X.getD i 0 - 1 / X.getD (i + 1) 0 else 0)

namespace PhiCert

/-- The contribution of one interval `(a, b)` (per unit of `vals`). -/
def phiTerm (m K : ℕ) (a b : ℚ) : ℚ :=
  (∑ k ∈ Finset.Icc 1 K, (1 / ((k : ℚ) + a) - 1 / ((k : ℚ) + b))) +
    if (1 / m : ℚ) ≤ a then 1 / a - 1 / b else 0

theorem phiSum_eq (m K : ℕ) (X : List ℚ) (vals : List ℕ) :
    phiSum m K X vals = ∑ i ∈ Finset.range (X.length - 1),
      (vals.getD i 0 : ℚ) * phiTerm m K (X.getD i 0) (X.getD (i + 1) 0) := rfl

theorem phiSum_cons (m K : ℕ) (α β : ℚ) (rest : List ℚ) (v : ℕ) (vs : List ℕ) :
    phiSum m K (α :: β :: rest) (v :: vs) =
      v * phiTerm m K α β + phiSum m K (β :: rest) vs := by
  rw [phiSum_eq, phiSum_eq]
  simp only [List.length_cons, Nat.add_sub_cancel]
  rw [Finset.sum_range_succ', add_comm]
  simp

theorem phiSum_nil_vals (m K : ℕ) (X : List ℚ) : phiSum m K X [] = 0 := by
  simp [phiSum_eq]

/-! ## The fixed-point computation -/

/-- `∑_{k=1}^{K} ⌊num / ((k dₐ + nₐ)(k d_b + n_b))⌋`. -/
def kSum (num na da nb db : ℕ) : ℕ → ℕ
  | 0 => 0
  | k + 1 => Nat.add (Nat.div num
      (Nat.mul (Nat.add (Nat.mul (k + 1) da) na) (Nat.add (Nat.mul (k + 1) db) nb)))
      (kSum num na da nb db k)

/-- Lower bound for `S · phiTerm m K (nₐ/dₐ) (n_b/d_b)`. -/
def termLB (S m K na da nb db : ℕ) : ℕ :=
  let num := Nat.mul S (Nat.sub (Nat.mul da nb) (Nat.mul db na))
  Nat.add (kSum num na da nb db K)
    (cond (Nat.ble da (Nat.mul m na)) (Nat.div num (Nat.mul na nb)) 0)

/-- Lower bound for `S · phiSum m K X vals`. -/
def sumLB (S m K : ℕ) : List ℚ → List ℕ → ℕ
  | α :: β :: rest, v :: vs =>
    Nat.add (Nat.mul v (termLB S m K α.num.toNat α.den β.num.toNat β.den))
      (sumLB S m K (β :: rest) vs)
  | _, _ => 0

/-- The `j`-th chunk (of `C` intervals) of `sumLB`. -/
def sumChunk (S m K C : ℕ) (X : List ℚ) (vals : List ℕ) (j : ℕ) : ℕ :=
  sumLB S m K ((X.drop (j * C)).take (C + 1)) ((vals.drop (j * C)).take C)

theorem one_div_nat_add (k na da : ℕ) (hda : 0 < da) :
    1 / ((k : ℚ) + (na : ℚ) / da) = da / (k * da + na) := by
  have : (0 : ℚ) < da := by exact_mod_cast hda
  field_simp

theorem kSum_le (S na da nb db : ℕ) (hda : 0 < da) (hdb : 0 < db) (hab : db * na ≤ da * nb) :
    ∀ K : ℕ, (kSum (S * (da * nb - db * na)) na da nb db K : ℚ) ≤
      S * ∑ k ∈ Finset.Icc 1 K, (1 / ((k : ℚ) + na / da) - 1 / ((k : ℚ) + nb / db))
  | 0 => by simp [kSum]
  | K + 1 => by
    rw [kSum, Finset.sum_Icc_succ_top (by omega), mul_add]
    simp only [Nat.add_eq, Nat.mul_eq, nat_div_eq]
    rw [Nat.cast_add, add_comm]
    refine add_le_add (kSum_le S na da nb db hda hdb hab K) ?_
    refine (Nat.cast_div_le).trans (le_of_eq ?_)
    have hda' : (0 : ℚ) < da := by exact_mod_cast hda
    have hdb' : (0 : ℚ) < db := by exact_mod_cast hdb
    have h1 : ((K : ℚ) + 1 + na / da) = ((K + 1) * da + na) / da := by field_simp
    have h2 : ((K : ℚ) + 1 + nb / db) = ((K + 1) * db + nb) / db := by field_simp
    have h3 : (0 : ℚ) < (K + 1) * da + na := by positivity
    have h4 : (0 : ℚ) < (K + 1) * db + nb := by positivity
    push_cast [Nat.cast_sub hab]
    rw [h1, h2, one_div_div, one_div_div]
    field_simp
    ring

theorem termLB_le (S m K na da nb db : ℕ) (hm : 0 < m) (hda : 0 < da) (hdb : 0 < db)
    (hab : db * na ≤ da * nb) :
    (termLB S m K na da nb db : ℚ) ≤ S * phiTerm m K (na / da) (nb / db) := by
  unfold termLB phiTerm
  simp only [Nat.add_eq, Nat.mul_eq, Nat.sub_eq, nat_div_eq, Nat.cast_add, mul_add]
  refine add_le_add (kSum_le S na da nb db hda hdb hab K) ?_
  have hda' : (0 : ℚ) < da := by exact_mod_cast hda
  have hdb' : (0 : ℚ) < db := by exact_mod_cast hdb
  have hm' : (0 : ℚ) < m := by exact_mod_cast hm
  have hS : (0 : ℚ) ≤ S := Nat.cast_nonneg S
  cases h : Nat.ble da (m * na)
  · -- our bound is `0`
    simp only [Bool.cond_false, Nat.cast_zero]
    split_ifs with h'
    · have ha : (0 : ℚ) < na / da := lt_of_lt_of_le (by positivity) h'
      have hab' : (na : ℚ) / da ≤ nb / db := by
        rw [div_le_div_iff₀ hda' hdb']; exact_mod_cast (by linarith [hab] : na * db ≤ nb * da)
      have : 1 / ((nb : ℚ) / db) ≤ 1 / (na / da) := one_div_le_one_div_of_le ha hab'
      nlinarith
    · simp
  · simp only [Bool.cond_true]
    have hle : da ≤ m * na := by rw [← Nat.ble_eq, h]
    have hna : 0 < na := by
      rcases Nat.eq_zero_or_pos na with h0 | h0
      · rw [h0] at hle; omega
      · exact h0
    have hnb : 0 < nb := by
      rcases Nat.eq_zero_or_pos nb with h0 | h0
      · rw [h0] at hab; have : 0 < db * na := Nat.mul_pos hdb hna; omega
      · exact h0
    have hna' : (0 : ℚ) < na := by exact_mod_cast hna
    have hnb' : (0 : ℚ) < nb := by exact_mod_cast hnb
    have hcond : (1 / m : ℚ) ≤ na / da := by
      rw [div_le_div_iff₀ hm' hda']
      have : (da : ℚ) ≤ m * na := by exact_mod_cast hle
      linarith
    simp only [hcond, ↓reduceIte]
    refine (Nat.cast_div_le).trans (le_of_eq ?_)
    push_cast [Nat.cast_sub hab]
    field_simp

theorem sumLB_le (S m K : ℕ) (hm : 0 < m) :
    ∀ (X : List ℚ) (vals : List ℕ), X.Pairwise (· < ·) → (∀ q ∈ X, 0 ≤ q) →
      (sumLB S m K X vals : ℚ) ≤ S * phiSum m K X vals
  | α :: β :: rest, v :: vs, hX, hnn => by
    rw [sumLB, phiSum_cons]
    simp only [Nat.add_eq, Nat.mul_eq, Nat.cast_add, Nat.cast_mul, mul_add]
    have ih := sumLB_le S m K hm (β :: rest) vs hX.of_cons
      fun q hq => hnn q (List.mem_cons_of_mem _ hq)
    refine add_le_add ?_ ih
    have hα : 0 ≤ α := hnn α (by simp)
    have hβ : 0 ≤ β := hnn β (by simp)
    have hlt : α < β := List.rel_of_pairwise_cons hX (by simp)
    have eα : ((α.num.toNat : ℕ) : ℚ) / α.den = α := by
      have h := Rat.num_div_den α
      rw [← Int.toNat_of_nonneg (Rat.num_nonneg.2 hα), Int.cast_natCast] at h
      exact h
    have eβ : ((β.num.toNat : ℕ) : ℚ) / β.den = β := by
      have h := Rat.num_div_den β
      rw [← Int.toNat_of_nonneg (Rat.num_nonneg.2 hβ), Int.cast_natCast] at h
      exact h
    have hab : β.den * α.num.toNat ≤ α.den * β.num.toNat := by
      have : ((α.num.toNat : ℕ) : ℚ) / α.den ≤ ((β.num.toNat : ℕ) : ℚ) / β.den := by
        rw [eα, eβ]; exact hlt.le
      rw [div_le_div_iff₀ (by exact_mod_cast α.den_pos) (by exact_mod_cast β.den_pos)] at this
      have h' : ((β.den * α.num.toNat : ℕ) : ℚ) ≤ ((α.den * β.num.toNat : ℕ) : ℚ) := by
        push_cast; linarith
      exact_mod_cast h'
    have := termLB_le S m K _ _ _ _ hm α.den_pos β.den_pos hab
    rw [eα, eβ] at this
    have hv : (0 : ℚ) ≤ v := Nat.cast_nonneg v
    calc (v : ℚ) * (termLB S m K α.num.toNat α.den β.num.toNat β.den : ℚ)
        ≤ v * (S * phiTerm m K α β) := mul_le_mul_of_nonneg_left this hv
      _ = S * (v * phiTerm m K α β) := by ring
  | [], _, _, _ => by simp [sumLB, phiSum_eq]
  | [_], _, _, _ => by simp [sumLB, phiSum_eq]
  | _ :: _ :: _, [], _, _ => by simp [sumLB, phiSum_nil_vals]

theorem sumLB_split (S m K : ℕ) :
    ∀ (n : ℕ) (X : List ℚ) (vals : List ℕ),
      sumLB S m K X vals = sumLB S m K (X.take (n + 1)) (vals.take n) +
        sumLB S m K (X.drop n) (vals.drop n)
  | 0, X, vals => by
    rcases X with _ | ⟨α, _ | ⟨β, rest⟩⟩ <;> simp [sumLB]
  | n + 1, α :: β :: rest, v :: vs => by
    have := sumLB_split S m K n (β :: rest) vs
    simp only [List.take_succ_cons, List.drop_succ_cons] at this ⊢
    rw [sumLB, sumLB, this]
    simp only [Nat.add_eq]
    omega
  | n + 1, [], vals => by simp [sumLB]
  | n + 1, [_], vals => by simp [sumLB]
  | n + 1, _ :: _ :: _, [] => by simp [sumLB]

theorem sumLB_chunks (S m K C : ℕ) :
    ∀ (N : ℕ) (X : List ℚ) (vals : List ℕ),
      sumLB S m K X vals = (∑ j ∈ Finset.range N, sumChunk S m K C X vals j) +
        sumLB S m K (X.drop (N * C)) (vals.drop (N * C))
  | 0, X, vals => by simp
  | N + 1, X, vals => by
    rw [sumLB_chunks S m K C N X vals, Finset.sum_range_succ,
      sumLB_split S m K C (X.drop (N * C)) (vals.drop (N * C))]
    simp only [sumChunk, List.drop_drop]
    rw [show N * C + C = (N + 1) * C by ring]
    ring

theorem sumLB_eq_chunks (S m K C N : ℕ) (X : List ℚ) (vals : List ℕ)
    (hN : vals.length ≤ N * C) :
    sumLB S m K X vals = ∑ j ∈ Finset.range N, sumChunk S m K C X vals j := by
  rw [sumLB_chunks S m K C N X vals, List.drop_eq_nil_of_le hN]
  rcases X.drop (N * C) with _ | ⟨α, _ | ⟨β, rest⟩⟩ <;> simp [sumLB]

theorem nonneg_of_head {X : List ℚ} (hh : X.head? = some 0) (hX : X.Pairwise (· < ·)) :
    ∀ q ∈ X, 0 ≤ q := by
  rcases X with _ | ⟨a, rest⟩
  · simp
  · simp only [List.head?_cons, Option.some.injEq] at hh
    subst hh
    intro q hq
    rcases List.mem_cons.1 hq with rfl | hq
    · exact le_rfl
    · exact (List.rel_of_pairwise_cons hX hq).le

/-- From a checked `φ` certificate and chunk values, a lower bound for `phiSum`. -/
theorem phiSum_ge_of_chunks {η₀ : ℕ} {zs ps : List ℕ} {X : List ℚ} {vals : List ℕ}
    (hc : checkPhiCert η₀ zs ps X vals = true) (S m K C N : ℕ) (hS : 0 < S) (hm : 0 < m)
    (hN : vals.length ≤ N * C) (lo : List ℕ)
    (hlo : ∀ j < N, lo.getD j 0 ≤ sumChunk S m K C X vals j) (B : ℕ)
    (hB : B ≤ ∑ j ∈ Finset.range N, lo.getD j 0) :
    (B : ℚ) / S ≤ phiSum m K X vals := by
  obtain ⟨-, -, hh, -⟩ := globalOK_of_checkPhiCert hc
  have hX := (checkPhiCert_length hc).2
  have h1 := sumLB_le S m K hm X vals hX (nonneg_of_head hh hX)
  rw [sumLB_eq_chunks S m K C N X vals hN] at h1
  have h2 : B ≤ ∑ j ∈ Finset.range N, sumChunk S m K C X vals j :=
    hB.trans (Finset.sum_le_sum fun j hj => hlo j (Finset.mem_range.1 hj))
  have hS' : (0 : ℚ) < S := by exact_mod_cast hS
  rw [div_le_iff₀ hS']
  have h2' : (B : ℚ) ≤ ((∑ j ∈ Finset.range N, sumChunk S m K C X vals j : ℕ) : ℚ) := by
    exact_mod_cast h2
  push_cast at h1 h2'
  linarith

theorem sumChunksA_le : ∀ j < 35, sumChunksA.getD j 0 ≤
    sumChunk 1000000000 72 20 100 XA valsA j := by
  intro j hj
  interval_cases j <;> decide +kernel

theorem sumChunksB_le : ∀ j < 23, sumChunksB.getD j 0 ≤
    sumChunk 1000000000 57 20 100 XB valsB j := by
  intro j hj
  interval_cases j <;> decide +kernel

end PhiCert

open PhiCert

/-- `I' ≥ 678.6` in case A (`m̂ = 72`, `K = 20`). -/
theorem phiSumA_ge : (678.6 : ℚ) ≤ phiSum 72 20 XA valsA := by
  have := phiSum_ge_of_chunks checkA 1000000000 72 20 100 35 (by norm_num) (by norm_num)
    (by decide +kernel) sumChunksA sumChunksA_le 678600000000
    (by simp [Finset.sum_range_succ, sumChunksA])
  norm_num at this ⊢
  linarith

/-- `I' ≥ 774.1` in case B (`m̂ = 57`, `K = 20`). -/
theorem phiSumB_ge : (774.1 : ℚ) ≤ phiSum 57 20 XB valsB := by
  have := phiSum_ge_of_chunks checkB 1000000000 57 20 100 23 (by norm_num) (by norm_num)
    (by decide +kernel) sumChunksB sumChunksB_le 774100000000
    (by simp [Finset.sum_range_succ, sumChunksB])
  norm_num at this ⊢
  linarith

end OddZeta
