import OddZeta.Cert.Machinery

/-!
# Data of the saddle-point certificates

Generated by `scripts/saddle_lean_data.py` from `scripts/saddle_data.json`.
-/

set_option linter.style.longLine false

namespace OddZeta.Cert

/-- The certificate data for case (A). -/
def dataA : SData where
  ur := mkRat (-59075865825851509369) 100000000000000000000
  ui := mkRat (-972268849128457423063) 100000000000000000000
  vr := mkRat (-269) 500
  vi := mkRat (843) 1000
  x1 := mkRat (-3) 2
  rho := mkRat (1) 10000000000
  Y := (10000 : ℚ)
  V := mkRat (10001) 10000
  m := mkRat (1) 2
  M3 := mkRat (1) 10
  c := mkRat (1) 5
  H := (-939 : ℚ)
  m0 := (-16 : ℤ)
  prec := 60
  rayL := [mkRat (-2562705) 512, mkRat (-2568115) 1024, mkRat (-1289467) 1024, mkRat (-650143) 1024, mkRat (-330481) 1024, mkRat (-85325) 512, mkRat (-90735) 1024, mkRat (-50777) 1024, mkRat (-15399) 512, mkRat (-20809) 1024, mkRat (-7907) 512, mkRat (-13317) 1024, mkRat (-3017) 256, mkRat (-2861) 256]
  rayB := mkRat (-1056568849118457423063) 100000000000000000000
  horL := []
  horB := mkRat (-112875865815851509369) 100000000000000000000
  verA := mkRat (-887968849138457423063) 100000000000000000000
  verL := [mkRat (-6819) 1024, mkRat (-2273) 512]

/-- The certificate data for case (B). -/
def dataB : SData where
  ur := mkRat (120722308009257658639) 50000000000000000000
  ui := mkRat (-669892997425283778069) 100000000000000000000
  vr := mkRat (-353) 500
  vi := mkRat (177) 250
  x1 := mkRat (-1) 2
  rho := mkRat (1) 10000000000
  Y := (10000 : ℚ)
  V := (1 : ℚ)
  m := mkRat (4) 5
  M3 := mkRat (3) 10
  c := mkRat (1) 5
  H := (-1175 : ℚ)
  m0 := (-13 : ℤ)
  prec := 60
  rayL := [mkRat (-320237) 64, mkRat (-320711) 128, mkRat (-321659) 256, mkRat (-323555) 512, mkRat (-327347) 1024, mkRat (-83733) 512, mkRat (-15937) 128, mkRat (-87525) 1024, mkRat (-16885) 256, mkRat (-47555) 1024, mkRat (-18781) 512, mkRat (-13785) 512, mkRat (-11287) 512, mkRat (-5019) 256, mkRat (-17577) 1024, mkRat (-15079) 1024, mkRat (-6915) 512, mkRat (-12581) 1024, mkRat (-2833) 256, mkRat (-2677) 256, mkRat (-10083) 1024, mkRat (-4729) 512, mkRat (-4417) 512, mkRat (-4261) 512, mkRat (-8209) 1024, mkRat (-7897) 1024]
  rayB := mkRat (-740692997415283778069) 100000000000000000000
  horL := [mkRat (-229) 1024, mkRat (27) 512, mkRat (619) 1024, mkRat (37) 32]
  horB := mkRat (85422308014257658639) 50000000000000000000
  verA := mkRat (-599092997435283778069) 100000000000000000000
  verL := []

end OddZeta.Cert
