"""Generate `OddZeta/Family/PhiBase.lean`: the φ certificate for the base vector
`famBase = (150; 45; 48, 50, 53, 56, 60)` of the uniform family `η^(r)` (Section 8 of the note),
and the chunk values of the fixed-point lower bound for `phiSum 54 20 XBase valsBase`
(`m̂₀ = 54`, `K = 20`).

Same format and checks as `phi_cert.py` (whose checker simulation and fixed-point sums are reused).
For `η^(r)`, `φ(x) ≥ r φ̄(x)` with `φ̄` the function of the base vector, and the weighted sum of
`r φ̄` is `r` times that of `φ̄` (see `OddZeta/Family/Arith.lean`).

Usage: python3 phi_cert_base.py        (writes ../OddZeta/Family/PhiBase.lean, ~2 s)
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from phi import phi, breakpoints, mhat  # noqa: E402
from phi_cert import check, sum_chunks, phisum_exact, lean_list, CHUNK, SUM_S, SUM_K  # noqa: E402

E0, ZS, PS = 150, [45], [48, 50, 53, 56, 60]
BASE = dict(r=1, eta0=E0, eta=ZS + PS, q=len(ZS) + len(PS))
MHAT0 = 54
BOUND = '116.2'


def write_lean(X, vals, chunks_sum):
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'OddZeta', 'Family',
                        'PhiBase.lean')
    zs, ps = f'[{", ".join(map(str, ZS))}]', f'[{", ".join(map(str, PS))}]'
    xs = [f'({x.numerator}, {x.denominator})' for x in X]
    vs = [str(v) for v in vals]
    nch = (len(vals) + CHUNK - 1) // CHUNK   # chunks 0 .. nch - 1
    N = nch - 1
    assert len(vals) <= N * CHUNK + CHUNK - 1
    assert len(vals) <= nch * CHUNK
    chunks = '\n'.join(
        f'theorem checkBase_chunk_{j} : chunkOK {E0} {zs} {ps} XBase valsBase {j} = true := by\n'
        f'  decide +kernel\n' for j in range(nch))
    cases = '\n'.join(f'    | {j}, _ => checkBase_chunk_{j}' for j in range(nch))
    B = int(BOUND.replace('.', '')) * SUM_S // 10 ** (len(BOUND) - BOUND.index('.') - 1)
    assert B <= sum(chunks_sum)
    out = f'''import OddZeta.Phi.Sum

/-!
# φ certificate for the base vector of the uniform family

Generated by `scripts/phi_cert_base.py` (do not edit).  For the base vector
`famBase = (150; 45; 48, 50, 53, 56, 60)`, `XBase` is the list of breakpoints
(`phi.breakpoints`, {len(X)} points) and `valsBase[i]` the exact value of `φ̄` on
`(XBase[i], XBase[i+1])` (`phi.phi` at the midpoint).  The check is split into {nch} kernel
computations of {CHUNK} intervals each (`chunkOK`), assembled by `checkPhiCert_of_chunks`.

`phiSumBase_ge`: `I'(φ̄) = phiSum {MHAT0} {SUM_K} XBase valsBase ≥ {BOUND}` (`m̂₀ = {MHAT0}`, `K = {SUM_K}`), by the
fixed-point computation of `OddZeta/Phi/Sum.lean`.
-/

namespace OddZeta.PhiCert

/-- Breakpoints as (numerator, denominator) pairs. -/
def XBaseraw : List (ℕ × ℕ) := {lean_list(xs, 8)}

/-- The breakpoints `XBase` (strictly increasing, from `0` to `1`). -/
def XBase : List ℚ := XBaseraw.map fun p => mkRat p.1 p.2

/-- The values of `φ̄` on the intervals of `XBase`. -/
def valsBase : List ℕ := {lean_list(vs, 24)}

/-- The chunk values `sumChunk {SUM_S} {MHAT0} {SUM_K} {CHUNK} XBase valsBase j` of the fixed-point
lower bound for `phiSum` (checked in `sumChunksBase_le`). -/
def sumChunksBase : List ℕ := {lean_list([str(v) for v in chunks_sum], 5)}

{chunks}
/-- The certificate for the base vector is valid. -/
theorem checkBase : checkPhiCert {E0} {zs} {ps} XBase valsBase = true :=
  checkPhiCert_of_chunks (by decide +kernel) {N} (by decide +kernel) fun j hj =>
    match j, hj with
{cases}
    | _ + {nch}, h => absurd h (by omega)

theorem sumChunksBase_le : ∀ j < {nch}, sumChunksBase.getD j 0 ≤
    sumChunk {SUM_S} {MHAT0} {SUM_K} {CHUNK} XBase valsBase j := by
  intro j hj
  interval_cases j <;> decide +kernel

end OddZeta.PhiCert

namespace OddZeta

open PhiCert

/-- `I'(φ̄) ≥ {BOUND}` for the base vector (`m̂₀ = {MHAT0}`, `K = {SUM_K}`). -/
theorem phiSumBase_ge : ({BOUND} : ℚ) ≤ phiSum {MHAT0} {SUM_K} XBase valsBase := by
  have := phiSum_ge_of_chunks checkBase {SUM_S} {MHAT0} {SUM_K} {CHUNK} {nch} (by norm_num) (by norm_num)
    (by decide +kernel) sumChunksBase sumChunksBase_le {B}
    (by simp [Finset.sum_range_succ, sumChunksBase])
  norm_num at this ⊢
  linarith

end OddZeta
'''
    open(path, 'w').write(out)
    return path


def main():
    m0, ms = mhat(BASE)
    assert m0 == MHAT0
    X = breakpoints(BASE)
    vals = [phi(BASE, (X[i] + X[i + 1]) / 2) for i in range(len(X) - 1)]
    st = {}
    bad = check(E0, ZS, PS, X, vals, st)
    print('base: breakpoints', len(X), 'max phi', max(vals), 'failures', len(bad), st)
    for b in bad[:20]:
        print('   ', b)
    assert not bad
    ch = sum_chunks(MHAT0, X, vals)
    ex = phisum_exact(MHAT0, SUM_K, X, vals)
    lo = sum(ch)
    print('  phiSum: fixed-point lower bound', lo / SUM_S, 'exact', float(ex),
          'sound', lo <= SUM_S * ex, 'chunks', len(ch))
    print('  wrote', write_lean(X, vals, ch))


if __name__ == '__main__':
    main()
